### ISSUE TITLE
[Bug]: "Cannot install swebench" in `make build`

### ISSUE THREAD

**Issue by dpfried** [OpenDevin/OpenDevin#2528] opened 2024-06-19 18:14 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

When running `make build` I get the following error:

```
Package operations: 1 install, 0 updates, 0 removals

  - Installing swebench (1.1.5 7b0c4b1): Failed

  LocationValueError

  No host specified.
  ```

### Current OpenDevin version

```bash
0.6.2 . Git commit: 5ae647f5c260d1f29a1d96c4610fca485bda46d7 on main from June 17th 2024
```

### Installation and Configuration

```bash
conda create -n opendevin python=3.11
conda activate opendevin
conda install conda-forge::nodejs conda-forge::poetry
make build
```
### Model and Agent

N/A

### Operating System

Mac OS, Sonoma 14.4

### Logs, Errors, Screenshots, and Additional Context

Here's the output of `conda list`:

```
brotli-python             1.0.9           py311h313beb8_8
bzip2                     1.0.8                h80987f9_6
ca-certificates           2024.3.11            hca03da5_0
cachecontrol              0.14.0          py311hca03da5_1
cachecontrol-with-filecache 0.14.0          py311hca03da5_1
certifi                   2024.6.2        py311hca03da5_0
cffi                      1.16.0          py311h80987f9_1
charset-normalizer        2.0.4              pyhd3eb1b0_0
cleo                      2.1.0           py311hca03da5_0
colorama                  0.4.6           py311hca03da5_0
crashtest                 0.4.1           py311hca03da5_0
distlib                   0.3.8           py311hca03da5_0
dulwich                   0.21.3          py311h80987f9_0
filelock                  3.13.1          py311hca03da5_0
icu                       73.2                 hc8870d7_0    conda-forge
idna                      3.7             py311hca03da5_0
importlib-metadata        7.0.1           py311hca03da5_0
importlib_metadata        7.0.1                hd3eb1b0_0
jaraco.classes            3.2.1              pyhd3eb1b0_0
keyring                   24.3.1          py311hca03da5_0
libblas                   3.9.0           16_osxarm64_openblas    conda-forge
libcblas                  3.9.0           16_osxarm64_openblas    conda-forge
libcxx                    17.0.6               h5f092b4_0    conda-forge
libexpat                  2.6.2                hebf3989_0    conda-forge
libffi                    3.4.4                hca03da5_1
libgfortran               5.0.0           11_3_0_hca03da5_28
libgfortran5              11.3.0              h009349e_28
liblapack                 3.9.0           16_osxarm64_openblas    conda-forge
libopenblas               0.3.21               h269037a_0
libsqlite                 3.46.0               hfb93653_0    conda-forge
libuv                     1.48.0               h93a5062_0    conda-forge
libzlib                   1.3.1                hfb2fe0b_1    conda-forge
llvm-openmp               14.0.6               hc6e5704_0
more-itertools            10.1.0          py311hca03da5_0
msgpack-python            1.0.3           py311h48ca7d4_0
ncurses                   6.5                  hb89a1cb_0    conda-forge
nodejs                    20.12.2              h3b52c9b_0    conda-forge
numpy                     2.0.0           py311h4268184_0    conda-forge
openssl                   3.3.1                hfb2fe0b_0    conda-forge
packaging                 23.2            py311hca03da5_0
pexpect                   4.8.0              pyhd3eb1b0_3
pip                       24.0            py311hca03da5_0
pkginfo                   1.10.0          py311hca03da5_0
platformdirs              3.10.0          py311hca03da5_0
poetry                    1.8.3           osx_pyh534df25_1    conda-forge
poetry-core               1.9.0              pyhd8ed1ab_0    conda-forge
poetry-plugin-export      1.8.0              pyhd8ed1ab_0    conda-forge
ptyprocess                0.7.0              pyhd3eb1b0_2
pycparser                 2.21               pyhd3eb1b0_0
pyproject_hooks           1.0.0           py311hca03da5_0
pysocks                   1.7.1           py311hca03da5_0
python                    3.11.9          h932a869_0_cpython    conda-forge
python-build              1.2.1              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.20.0             pyhd8ed1ab_0    conda-forge
python-installer          0.7.0           py311hca03da5_0
python_abi                3.11                    4_cp311    conda-forge
rapidfuzz                 3.5.2           py311h313beb8_0
readline                  8.2                  h1a28f6b_0
requests                  2.32.2          py311hca03da5_0
requests-toolbelt         1.0.0           py311hca03da5_0
setuptools                69.5.1          py311hca03da5_0
shellingham               1.5.0           py311hca03da5_0
tk                        8.6.13               h5083fa2_1    conda-forge
tomli                     2.0.1           py311hca03da5_0
tomlkit                   0.12.5             pyha770c72_0    conda-forge
trove-classifiers         2023.10.18      py311hca03da5_0
tzdata                    2024a                h04d1e81_0
urllib3                   2.2.1           py311hca03da5_0
virtualenv                20.26.1         py311hca03da5_0
wheel                     0.43.0          py311hca03da5_0
xattr                     1.1.0           py311h05b510d_0    conda-forge
xz                        5.4.6                h80987f9_1
zipp                      3.17.0          py311hca03da5_0
zlib                      1.3.1                hfb2fe0b_1    conda-forge
```

**Comment by xingyaoww** [comment] 2024-06-19 19:40
Very strange... I tried to reproduce it on the provided commit (`5ae647f5c260d1f29a1d96c4610fca485bda46d7`) and the latest `main` (`c4ad3b8f479e32e449d20a31797dd2ce379ab48a`), and it seems to be running fine with me.

The `package.lock` looks ok: https://github.com/OpenDevin/OpenDevin/blob/main/poetry.lock#L6330-L6354
And the `pyproject.toml` as well: https://github.com/OpenDevin/OpenDevin/blob/main/pyproject.toml#L76

<img width="498" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/38853559/54f2eb87-25b8-40f5-8f7a-6fdfe82f1f7e">

For debugging, i wonder if running `pip install git+https://github.com/OpenDevin/SWE-bench.git@7b0c4b1c249ed4b4600a5bba8afb916d543e034a` works on your setup? If not, might there be some issue with the GitHub connection?

**Comment by dpfried** [comment] 2024-06-20 15:53
Thank you Xingyao! Yes, that pip install command works for me, with output:
```
...
Building wheels for collected packages: swebench
  Building wheel for swebench (pyproject.toml) ... done
  Created wheel for swebench: filename=swebench-1.1.5-py3-none-any.whl size=98488 sha256=2e52ac36d9a0fb3440cdec2d3561556e95495b8328b07caba4212d3fd7a1793a
  Stored in directory: /Users/dfried/Library/Caches/pip/wheels/cd/a8/bb/d01c7fa3d4727210d497578cf1824b113ddf55aee4929799e7
Successfully built swebench
Installing collected packages: pytz, xxhash, tzdata, typing-extensions, tqdm, soupsieve, smmap, six, pyyaml, python-dotenv, pygments, pyarrow-hotfix, pyarrow, multidict, mdurl, fsspec, frozenlist, fastcore, dill, chardet, attrs, yarl, python-dateutil, multiprocess, markdown-it-py, huggingface-hub, gitdb, ghapi, beautifulsoup4, aiosignal, rich, pandas, GitPython, aiohttp, datasets, swebench
Successfully installed GitPython-3.1.43 aiohttp-3.9.5 aiosignal-1.3.1 attrs-23.2.0 beautifulsoup4-4.12.3 chardet-5.2.0 datasets-2.20.0 dill-0.3.8 fastcore-1.5.46 frozenlist-1.4.1 fsspec-2024.5.0 ghapi-1.0.5 gitdb-4.0.11 huggingface-hub-0.23.4 markdown-it-py-3.0.0 mdurl-0.1.2 multidict-6.0.5 multiprocess-0.70.16 pandas-2.2.2 pyarrow-16.1.0 pyarrow-hotfix-0.6 pygments-2.18.0 python-dateutil-2.9.0.post0 python-dotenv-1.0.1 pytz-2024.1 pyyaml-6.0.1 rich-13.7.1 six-1.16.0 smmap-5.0.1 soupsieve-2.5 swebench-1.1.5 tqdm-4.66.4 typing-extensions-4.12.2 tzdata-2024.1 xxhash-3.4.1 yarl-1.9.4
```

But I'm still getting the same error ("No host specified") when running `make build`, so not sure what's happening. 

Since I was able to install via pip though, I'll see if I can go ahead with swebench evals.

**Comment by sb-git-cloud** [comment] 2024-06-22 02:11
I get the same error for both commits (`5ae647f5c260d1f29a1d96c4610fca485bda46d7`) and the latest main (`c4ad3b8f479e32e449d20a31797dd2ce379ab48a`).

**Comment by sb-git-cloud** [comment] 2024-06-25 02:57
Hey can you try running `poetry self update`? This did the trick for me.

**Comment by Jiayi-Pan** [comment] 2024-06-25 03:03
@sb-git-cloud 's `poetry self update` works for me!

**Comment by xingyaoww** [comment] 2024-07-04 18:03
Close the issue since it seems to be resolved.

**Closed by xingyaoww** 2024-07-04 18:03 UTC
Labels: bug, severity:medium

**Comment by dpfried** [comment] 2024-07-05 02:09
Yes, it worked for me too (took a bit to get to try it, sorry) -- thanks!

**Comment by fovi-com** [comment] 2024-08-26 03:50
I just had this problem too with both the main HEAD and 0.9.0 tag on a fresh install on MacOS.  
The problem is that pyproject.toml specifies a git repo instead of the 2.0.12 that is in the poetry.lock for swebench:

pyproject.toml 
```
114   [tool.poetry.group.evaluation.dependencies]
...
119 - swebench = { git = "https://github.com/All-Hands-AI/SWE-bench.git" }
119 + swebench = "*" # { git = "https://github.com/All-Hands-AI/SWE-bench.git" }
```

**Comment by jimwhite** [comment] 2024-08-26 04:04
I just had this problem too with both the main HEAD and 0.9.0 tag on a fresh install on MacOS.  
The problem is that pyproject.toml specifies a git repo instead of the 2.0.12 that is in the poetry.lock for swebench:

pyproject.toml 
```
114   [tool.poetry.group.evaluation.dependencies]
...
119 - swebench = { git = "https://github.com/All-Hands-AI/SWE-bench.git" }
119 + swebench = "*" 
```

**Comment by xingyaoww** [comment] 2024-08-28 03:15
@jimwhite do you mind share more about your setup (e.g., commit ID)? What was the exact error message? Feel free to start a separate issue to share these info -- i think the issue you encountered is probably different than the current issue.

**Comment by diwu-sf** [comment] 2024-10-20 00:11
I can reproduce this problem and i think it is due to the conda / miniconda poetry being slightly out of date, running `poetry self update` will fix this issue.
