### ISSUE TITLE
Option to interupt the task and give a new instruction

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#2703] opened 2024-06-30 09:43 UTC
**What problem or use case are you trying to solve?**
Right now it always want to run things like a server or install the whole project via terminal.
It you should be able to interupt the Agent when giving a new instruction.

**Describe the UX of the solution you'd like**

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**
![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/9f7da685-bbb9-4299-8f4c-b424a8f8949f)

**Comment by mamoodi** [comment] 2024-06-30 15:32
Closing as a duplicate of adding a stop button which will effectively do the same thing. https://github.com/OpenDevin/OpenDevin/issues/2703

**Closed** 2024-06-30 15:33 UTC
Labels: enhancement

**Comment by tobitege** [comment] 2024-06-30 15:35
Will be fixed by https://github.com/OpenDevin/OpenDevin/pull/2602/ but takes a little time, waiting for other dependencies to go first.
