### ISSUE TITLE
[Bug]: OpenDevin stuck in "Error during task loop: Agent task already running" after initial task

### ISSUE THREAD

**Issue by frankxu2004** [OpenDevin/OpenDevin#1512] opened 2024-05-02 06:49 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Now if you run the default monologue agent, and completes a first task, the second task, or all next user inputs will result in error message: Error during task loop: Agent task already running

cc @xingyaoww 

### Current Version

```bash
main branch
```

### Installation and Configuration

```bash
make run
```

### Model and Agent

- GPT 3.5 
- MonologueAgent

### Reproduction Steps

1. Start  `make run`
2. Input some tasks, wait for it to finish
3. Input some other stuff, throws error

### Logs, Errors, Screenshots, and Additional Context

![image](https://github.com/OpenDevin/OpenDevin/assets/6738274/9ad79a38-0d3f-4dfb-989f-91e32b3583ce)

**Comment by SmartManoj** [comment] 2024-05-02 07:33
Add logs

**Comment by amanape** [comment] 2024-05-02 10:57
It is not limited to the `MonologueAgent`. Attempting to pause or restart the agent also returns a "Current task state not recognized." message. 

```sh
==============
STEP 0

13:54:26 - PLAN
run ls in terminal
13:54:28 - ACTION
**CmdRunAction**
COMMAND:
ls
13:54:28 - OBSERVATION
CONTRIBUTING.md   Makefile   containers  frontend     pydoc-markdown.yml
CodeOfConduct.md  README.md  dev_config  logs         pyproject.toml
Development.md    agenthub   docs        opendevin    tests
LICENSE           cache      evaluation  poetry.lock


==============
STEP 1

13:54:31 - ACTION
It looks like you have the following files and directories in your current location:
- CONTRIBUTING.md
- Makefile
- containers
- frontend
- pydoc-markdown.yml
- CodeOfConduct.md
- README.md
- dev_config
- logs
- pyproject.toml
- Development.md
- agenthub
- docs
- opendevin
- tests
- LICENSE
- cache
- evaluation
- poetry.lock

How can I assist you further with these files?
```
Attempt to pause/restart agent:
```sh
INFO:     127.0.0.1:52296 - "DELETE /api/messages HTTP/1.1" 200 OK
INFO:     127.0.0.1:52298 - "DELETE /api/messages HTTP/1.1" 200 OK
INFO:     127.0.0.1:52300 - "DELETE /api/messages HTTP/1.1" 200 OK
```

**Comment by amanape** [comment] 2024-05-02 11:55
Duplicate of #1492

**Closed by amanape** 2024-05-02 11:55 UTC
Labels: bug, severity:medium
