### ISSUE TITLE
No logs printed anymore

### ISSUE THREAD

**Issue by stratte89** [OpenDevin/OpenDevin#744] opened 2024-04-05 02:20 UTC
#### Describe the bug

![319831896-5f28c4f3-1235-4dbd-bfb7-e55763847bbf](https://github.com/OpenDevin/OpenDevin/assets/101955267/4f0fa5d1-6792-468b-9bd4-090ed5e33d62)

Like described here https://github.com/OpenDevin/OpenDevin/issues/740

> [stratte89](https://github.com/stratte89) before i could see the steps in the opendevin server terminal. Because some model tend to stop replying in the frontend but still outputting on the terminal, without outputting any files in the workspace tho. you can see that on the pic. So it was good to check if there was a a problem to change the model, not waiting for output and thinking its just working, it was even saying its finnished although it did not write any code at all.
> 
> [foragerr](https://github.com/foragerr): They're seeing the effect of this: https://github.com/OpenDevin/OpenDevin/pull/378#discussion_r1552135801
> 
> The logs now don't print to console, instead they go into a file in ./logs .. I think.
> 
> [stratte89](https://github.com/stratte89)i'd love to print it again or having like another tab next to the browser with the live logs so you can check whats actually going on

#### Setup and configuration
**Current version**:

```bash
```

(base) stratte@stratte-MS-7D08:~/Schreibtisch/AI/OpenDevin4$ run `git log -n 1
> 

theres no output.

**My config.toml and environment vars** (be sure to redact API keys):
```toml
```
Ubuntu, oobabooga webui, i5 11400, 32gb ram, 3080.
LLM_API_KEY="na"
LLM_BASE_URL="http://0.0.0.0:5000/v1"
LLM_MODEL="openai/alpindale_Mistral-7B-v0.2-hf"
LLM_EMBEDDING_MODEL="lokal"
WORKSPACE_DIR="./workspace"
MAX_ITERATIONS=20000
**My model and agent** (you can see these settings in the UI):
* Model: Code-Mistral-7B-Q3_K_S.gguf
* Agent: Monologue

**Commands I ran to install and run OpenDevin**:
``` Make build, Make run
```

**Steps to Reproduce**:
1. just run it and tell it to do something and it wont show logs in the terminal.
2.
3.

**Logs, error messages, and screenshots**:

**Comment by dorbanianas** [comment] 2024-04-05 02:23
@stratte89 I'll move it to enhancement, because it's not a bug is that ok?

**Comment by stratte89** [comment] 2024-04-05 02:26
> @stratte89 I'll move it to enhancement, because it's not a bug is that ok?

Sure, would be nice to get a woraround to print them tho, since im testing all kinds of different LLM's and i need to see whats going on.

**Comment by dorbanianas** [comment] 2024-04-05 02:29
@rbren what do you think about this?

**Comment by foragerr** [comment] 2024-04-05 02:29
The change that causes this issue is

```
- @rm -f logs/pipe
- @mkfifo logs/pipe
- @cat logs/pipe | (make start-backend) &
- @echo 'test' | tee logs/pipe | (make start-frontend)
---
+ @poetry run nohup uvicorn opendevin.server.listen:app --port $(BACKEND_PORT) > logs/backend_$(shell date +'%Y%m%d_%H%M%S').log 2>&1 &
+ @echo "Waiting for the backend to start..."
+ @until nc -z localhost $(BACKEND_PORT); do sleep 0.1; done
+ @cd frontend && npm run start -- --port $(FRONTEND_PORT)
```

Pros for option # 1:
* Both frontend and backend logs go to console, easier to debug, watch activity
* Reuses `start-backend` and `start-frontend` make tasks.

Cons:
* Doesn't work on windows.
* Intermittently leaks processes when stopping server with Ctrl+C
* Backend takes longer to start, often the front end comes up first and shows an error - confusing for new users.

---

Pros for option # 2:
* Waits for backend to start before starting frontend

Cons:
* Logs go into files, less visible

**Comment by foragerr** [comment] 2024-04-05 02:31
@stratte89 for a workaround, you could `tail -f` the log files. Maybe something like `tail -f ./logs/*.log`

**Comment by stratte89** [comment] 2024-04-05 02:36
> tail -f ./logs/*.log

thank you, sorry i am very new to linux, just installed it because i couldn't make devin work on windows. I went to the logs directory and running your command but got me an error. I'd love to just change the code line where it can print it again like before, or i have to use the older version of devin again.

(base) stratte@stratte-MS-7D08:~/Schreibtisch/AI/OpenDevin4/logs$ tail -f ./logs/*.log
tail: './logs/*.log' kann nicht zum Lesen geöffnet werden: Datei oder Verzeichnis nicht gefunden
tail: Keine Dateien mehr übrig

**Comment by foragerr** [comment] 2024-04-05 02:40
if you're already in the logs folder, run just `tail -f *.log`

**Comment by dorbanianas** [comment] 2024-04-05 02:42
if you are using vscode you can move to the OpenDevin root directory and try to open the logs folder by typing `code logs` after that you will get the folder with different log files that contains the time of execution and try to open one of them and you will get the full stdout from the backend execution so with that you can have a saved version from each execution where you can try to benchmark after you finish your run what do you think about it now?

**Comment by stratte89** [comment] 2024-04-05 02:42
> tail -f *.log

![image](https://github.com/OpenDevin/OpenDevin/assets/101955267/030b98ca-643f-47c3-b829-43df64ae54e7)

alright that worked, but the log looks completely different from the log before?

**Comment by stratte89** [comment] 2024-04-05 02:45
> if you are using vscode you can move to the OpenDevin root directory and try to open the logs folder by typing `code logs` after that you will get the folder with different log files that contains the time of execution and try to open one of them and you will get the full stdout from the backend execution so with that you can have a saved version from each execution where you can try to benchmark after you finish your run what do you think about it now?

I am not using vscode and i dont want to run another application, and checking the logs after the run is not doing it for me since i have to see what its doing at the moment, because as you can see in the first picture, the output in the frontend chatbox stops but its still outputting in the terminal. This way i knew, that the llm isnt working correctly with devin and i could remove it and try the next one.

**Comment by dorbanianas** [comment] 2024-04-05 02:50
the log file if you open it using vscode it's like stdout it will get updated after each print in the stdout so it would be live version of the output just saved in a file.

**Comment by stratte89** [comment] 2024-04-05 02:54
> the log file if you open it using vscode it's like stdout it will get updated after each print in the stdout so it would be live version of the output just saved in a file.

Ah I see, well that would work theoretically, but I really don't feel like learning a new app again, since devin is working fine in the terminal like it is, and it was so easy seeing the logs in the server terminal, now having to install new software, asking gpt how to install everything etc... it took me days to make devin work, first on windows which did not work out, now ubuntu which messed up my bootmng which i didnt know, couldnt boot in my windows anymore only seeing the grub console in the bios... let's say it was a pain^^ so if there is a way by just removing a line in the code or adding to jetzt get it the way it was before would be awesome.

**Comment by stratte89** [comment] 2024-04-05 03:07
> > the log file if you open it using vscode it's like stdout it will get updated after each print in the stdout so it would be live version of the output just saved in a file. 
> 
> Ah I see, well that would work theoretically, but I really don't feel like learning a new app again, since devin is working fine in the terminal like it is, and it was so easy seeing the logs in the server terminal, now having to install new software, asking gpt how to install everything etc... it took me days to make devin work, first on windows which did not work out, now ubuntu which messed up my bootmng which i didnt know, couldnt boot in my windows anymore only seeing the grub console in the bios... let's say it was a pain^^ so if there is a way by just removing a line in the code or adding to just get it the way it was before would be awesome.
> 
> maybe using the tail -f *.log command while the server is running to just print the log and keep it updated in the server temrinal? or like in a tab next to the browser as mentioned before
well no hurry i just switched back to the older version

**Comment by dorbanianas** [comment] 2024-04-05 03:08
alright if that's the case you can simply try to run `make start-backend` in a terminal windows and after it get executed you can run `make start-frontend`

**Comment by dorbanianas** [comment] 2024-04-05 03:08
this would give you two windows one for backend and another for the frontend

**Comment by dorbanianas** [comment] 2024-04-05 03:08
let me know if there's any issues

**Comment by stratte89** [comment] 2024-04-05 03:15
> make start-frontend

perfect thx now the logs are back :)

**Comment by dorbanianas** [comment] 2024-04-05 03:17
Enjoy so I'm not sure if you think we should keep this or we can close it?

**Closed** 2024-04-05 03:19 UTC
Labels: enhancement

**Comment by dorbanianas** [comment] 2024-04-05 03:22
I think there's something they are working on it in the new UI stay tuned!
