### ISSUE TITLE
[Feature, Frontend] Streaming command line outputs to frontend

### ISSUE THREAD

**Issue by xingyaoww** [OpenDevin/OpenDevin#2747] opened 2024-07-02 15:25 UTC
> That's actually something I've hope to have for a while. But streaming to frontend (compared to streaming to stdout directly) might require us to re-write the whole event stream a bit to support token streaming, which could be pretty complicated in my understanding. I don't yet have a better idea so feel free to PR if you've got good ones ;)

I think adding `stream` to frontend may be a tricky one. Suggest to open a new issue to address it.

_Originally posted by @Umpire2018 in https://github.com/OpenDevin/OpenDevin/issues/892#issuecomment-2203504809_

Per discussion above, we hope to allow bash execution results to stream (token-by-token) to the FE for a better UX.

**Expected behavior**

https://github.com/OpenDevin/OpenDevin/assets/138990495/6f81af19-09f1-4e81-af69-be2dae65e96e

_Originally posted by @Umpire2018 in https://github.com/OpenDevin/OpenDevin/issues/892#issuecomment-2203297178_

**Comment by xingyaoww** [comment] 2024-07-03 14:49
@neubig oh yeah you are right - should we close this then?

**Comment by mamoodi** [comment] 2024-07-05 15:54
Closing as a duplicate of https://github.com/OpenDevin/OpenDevin/issues/1193

**Closed by mamoodi** 2024-07-05 15:54 UTC
Labels: enhancement
