### ISSUE TITLE
Exceeded your current quota (WSL Windows 11) Working

### ISSUE THREAD

**Issue by LewyCoda** [OpenDevin/OpenDevin#691] opened 2024-04-04 04:04 UTC
![opendevin error](https://github.com/OpenDevin/OpenDevin/assets/34385032/3c36d815-48a0-4e68-8abc-c41d17a6a2bd)

#### Describe the bug

picture in discription
#### Setup and configuration
**Current version**:

commit 78c196d95fde8cd73b642e5a51c0cf864f9bbf4c (HEAD -> main, origin/main, origin/HEAD)
Author: Anas DORBANI <95044293+dorbanianas@users.noreply.github.com>
Date:   Wed Apr 3 20:09:37 2024 +0000

    Add the description about the LMs Support (#674)

**My config.toml and environment vars** (be sure to redact API keys):
LLM_MODEL="gpt-3.5-turbo-16k-0613"
LLM_API_KEY="*******"
WORKSPACE_DIR="./workspace"

**My model and agent** (you can see these settings in the UI):
* Model: gpt-3.5-turbo-16k-0613
* Agent: MonologueAgent

**Commands I ran to install and run OpenDevin**:
    1  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
    2  source .bashrc
    3  nvm install 16
    4  nvm use 16
    5  sudo apt update
    6  sudo apt install -y python3.11
    7  python3.11
    8  pip install pipenv
    9  apt install python3-pip
   10  sudo apt install python3-pip
   11  python3 --version
   12  pip install pipenv
   13  git clone https://github.com/OpenDevin/OpenDevin.git
   14  cd OpenDevin
   15  pipenv --python 3.11
   16  apt install pipenv
   17  sudo apt install pipenv
   18  pipenv --python 3.11
   19  pipenv install
   20  pipenv shell
   21  cd frontend/
   22  npm install
   23  npm start
   24  clear
   25  cd ..
   26  ls
   27  nano config.toml.template
   28  ls
   29  nano README.md
   30  bash make build
   31  make build
   32  sudo make build
   33  docker
   34  clear
   35  cd frontend/
   36  ls
   37  nano vite.config.ts
   38  npm start
   39  nano vite.config.ts
   40  npm start
   41  clear
   42  ls
   43  nano README.md
   44  npm run build
   45  npm install monaco-editor
   46  npm run build
   47  npm start
   48  npm run build
   49  npm
   50  npm run dev
   51  npm test
   52  clear
   53  nano vite.config.ts
   54  npm start
   55  ls
   56  cd OpenDevin/
   57  LS
   58  ls
   59  make build
   60  sudo make build
   61  cd agenthub/
   62  ls
   63  nano README.md
   64  cd ..
   65  ls
   66  nano README.md
   67  bash make build
   68  bash
   69  pipenv shell
   70  clear
   71  bash make build
   72  make build
   73  ls
   74  nano config.toml
   75  cd frontend/
   76  cd ..
   77  make start-backend
   78  sudo apt update
   79  sudo apt install apt-transport-https ca-certificates curl software-properties-common
   80  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
   81  sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
   82  sudo apt update
   83  sudo apt install docker-ce
   84  make build
   85  docker
   86  docker ps -a
   87  docker ps
   88  sudo docker ps
   89  sudo make build
   90  nano Makefile
   91  sudo make build
   92  nano Makefile
   93  pip install urllib3
   94  sudo make build
   95  make build
   96  apt install docker-ce
   97  sudo usermod -aG docker ${USER}
   98  su - ${USER}
   99  python3.11 -m pip install --user pipenv
  100  python3.11 -m pipenv install -v
  101  docker
  102  docker ps -a
  103  docker images
  104  make run
  105  clear
  106  make start-backend
  107  pipenv install charset_normalizer
  108  make run
  109  nano Makefile
  110  make start-backend
  111  nano Makefile
  112  make run
  113  uivcorn
  114  uvicorn
  115  make start-backend
  116  nano Makefile
  117  python3.11 -m pip install --user pipenv
  118  nano Makefile
  119  make start-backend
  120  pipenv
  121  clear
  122  make start-backend
  123  python3.11 pipenv
  124  python3.11 -m pipenv
  125  nano Makefile
  126  make build
  127  nano Makefile
  128  make build
  129  make start-backend
  130  nano Makefile
  131  pipenv install charset_normalizer
  132  make start-backend
  133  python3.11 -m pipenv install charset_normalizer
  134  make start-backend
  135  python3 -m pipenv install charset_normalizer
  136  make start-backend
  137  nano Makefile
  138  make start-backend
  139  python
  140  python3.11
  141  clear
  142  pipenv install charset_normalizer
  143  pipenv install
  144  python3.11
  145  python3
  146  python
  147  python3
  148  clear
  149  pip install charset_normalizer
  150  python
  151  clear
  152  make start-backend
  153  clear
  154  cd ..
  155  ls
  156  cd OpenDevin/
  157  ls
  158  nano config.toml
  159  nano config.toml.template
  160  nano Makefile
  161  make start-backend
  162  pipenv i
  163  python3
  164  clear
  165  pip install openai
  166  clear
  167  python3
  168  clear
  169  make start-backend
  170  pip install llama_index
  171  make start-backend
  172  pip install llama_index.vector_stores
  173  pip install llama_index
  174  make start-backend
  175  pip install llama_index
  176  make start-backend
  177  pipenv install llama_index
  178  make start-backend
  179  pipenv install agenthub
  180  nano Pipfile
  181  python
  182  pipenv install poetry
  183  poetry
  184  clear
  185  python3
  186  clear
  187  poetry init
  188  clear
  189  python
  190  ls
  191  nano pyproject.toml
  192  python3
  193  ls
  194  nano Pipfile
  195  nano Makefile
  196  make start-backend
  197  nano Makefile
  198  make start-backend
  199  nano Makefile
  200  make start-backend
  201  llama_index
  202  python
  203  exit
  204  pip install --upgrade --force-reinstall llama_index
  205  make start-backend
  206  make build
  207  make start-backend
  208  pip list | grep llama_index
  209  echo $PYTHONPATH
  210  exit
  211  ls
  212  cd OpenDevin
  213  ls
  214  make run
  215  nano /home/lewy/OpenDevin/opendevin/controller/agent_controller.py
  216  ls
  217  nano config.toml
  218  make run
  219  clear
  220  nano config.toml
  221  clear
  222  exit
  223  ls
  224  cd OpenDevin/
  225  ls
  226  make build
  227  nano Makefile
  228  make build
  229  make setup-config
  230  make run
  231  nano Makefile
  232  make run
  233  nano Makefile
  234  make start-backend
  235  pip install charset_normalizer, urllib3
  236  sudo pip install charset_normalizer, urllib3
  237  sudo pip install charset_normalizer
  238  sudo pip install urllib3
  239  make start-backend
  240  nano Makefile
  241  make build
  242  nano Makefile
  243  make build
  244  make run
  245  nano Makefile
  246  make run
  247  nano Makefile
  248  make run
  249  nano Makefile
  250  make run
  251  nano Makefile
  252  make start-backend
  253  make start-frontend
  254  nano Makefile
  255  make start-backend
  256  pipenv shell
  257  make start-backend
  258  python
  259  python3
  260  make build
  261  make start-backend
  262  nano Makefile
  263  make build
  264  make start-backend
  265  pip install --upgrade --force-reinstall llama_index
  266  make start-backend
  267  pipenv shell
  268  pip install llama_index
  269  make start-backend
  270  nano Makefile
  271  pipenv
  272  pipenv shell
  273  uvicorn opendevin.server.listen:app --port 127.0.0.1:3000
  274  uvicorn opendevin.server.listen:app --port 3000
  275  python3 -m pipenv uvicorn opendevin.server.listen:app --port 3000
  276  python3 -m pipenv run uvicorn opendevin.server.listen:app --port 3000
  277  pipenv install --upgrade --force-reinstall llama_index
  278  pipenv install --force-reinstall llama_index
  279  pipenv install llama_index
  280  pipenv
  281  pipenv install
  282  pipenv sync
  283  python3 -m pipenv run uvicorn opendevin.server.listen:app --port 3000
  284  python3 -m pipenv install llama
  285  python3 -m pipenv run uvicorn opendevin.server.listen:app --port 3000
  286  python3 -m pipenv install llama_index
  287  python3 -m pipenv run uvicorn opendevin.server.listen:app --port 3000
  288  python3 -m pipenv install
  289  python3 -m pipenv run uvicorn opendevin.server.listen:app --port 3000
  290  python3 -m pipenv sync
  291  python3 -m pipenv install
  292  python3 -m pipenv run uvicorn opendevin.server.listen:app --port 3000
  293  nano /home/lewy/OpenDevin/agenthub/__init__.py
  294  nano /home/lewy/OpenDevin/agenthub/monologue_agent/utils/memory.py
  295  python3 -m pipenv run uvicorn opendevin.server.listen:app --port 3000
  296  python3
  297  ls
  298  make start-backend
  299  nano /home/lewy/OpenDevin/agenthub/monologue_agent/utils/memory.py
  300  python
  301  nano /home/lewy/OpenDevin/agenthub/monologue_agent/utils/memory.py
  302  python
  303  clear
  304  nano /home/lewy/OpenDevin/agenthub/monologue_agent/utils/memory.py
  305  pip install llama-index-vector-stores-chroma
  306  pipenv install llama-index-vector-stores-chroma
  307  python
  308  python3 -m pipenv install llama-index-vector-stores-chroma
  309  python3 -m pip install llama-index-vector-stores-chroma
  310  python
  311  clear
  312  make start-backend
  313  pip install llama-index-embeddings-huggingface
  314  && pip install llama-index-embeddings-instructor
  315  pip install llama-index-embeddings-instructor
  316  make start-backend
  317  make run
  318  nano /home/lewy/OpenDevin/agenthub/codeact_agent/codeact_agent.py
  319  make run
  320  ls
  321  clear
  322  ls
  323  nano config.toml
  324  make run
  325  clear
  326  ls
  327  nano config.toml
  328  naon config.toml.template
  329  nano config.toml.template
  330  make run
  331  clear
  332  ls
  333  nano config.toml
  334  make run
  335  clear
  336  make setup-config
  337  nano config.toml
  338  make setup-config
  339  ls
  340  ls workspace
  341  ls
  342  c d..
  343  cd ..
  344  ls
  345  cd OpenDevin/
  346  ls
  347  rm workspace
  348  rmdir workspace
  349  ls
  350  nano config.toml
  351  rm config.toml
  352  make setup-config
  353  ls
  354  mkdir worspace
  355  ls
  356  rm config.toml
  357  make setup-config
  358  rm config.toml
  359  rmdir worspace
  360  mkdir workspace
  361  make setup-config
  362  cd workspace/
  363  ls
  364  cd ..
  365  ls
  366  nano config.toml
  367  make run
  368  clear
  369  ls
  370  cd workspace/
  371  ls
  372  clear
  373  cd ..
  374  ls
  375  cd tests
  376  ls
  377  cd docs
  378  cd ..
  379  cd docs
  380  ls
  381  cd architecture/
  382  ls
  383  history
  384  cd ..
  385  make run
  386  npm install openai@^4.0.0
  387  npm update
  388  npm fund
  389  nano /home/lewy/OpenDevin/opendevin/controller/agent_controller.py
  390  make run
  391  clear
  392  ls
  393  make help
  394  clar
  395  clear
  396  make run
  397  clear
  398  ls
  399  cd dev_config/
  400  ls
  401  clear
  402  ls
  403  cd python
  404  ls
  405  nano ruff.toml
  406  nano mypy.ini
  407  cd ..
  408  cd..
  409  ls
  410  cd ..
  411  ls
  412  clear
  413  ls
  414  cd workspace
  415  ls
  416  cd ..
  417  cd logs
  418  ls
  419  nano pipe
  420  clear
  421  ls
  422  nano pipe
  423  python
  424  nano testAPI.py
  425  python3 testAPI.py
  426  curl https://api.openai.com/v1/engines   -H "Authorization: Bearer sk-****************************************************"
  427  cd ..
  428  ls
  429  rm config.toml
  430  cd frontend
  431  ls
  432  nano index.html
  433  make run
  434  cd ..
  435  make run
  436  clear
  437  git log -n 1
  438  log -n 1
  439  ls
  440  Openls
  441  ls
  442  cd OpenDevin/
  443  ls
  444  nano config.toml

**Steps to Reproduce**:
1.Make run
2.as
3.as

**Logs, error messages, and screenshots**:
aSD
#### Additional Context
sad

**Comment by LewyCoda** [comment] 2024-04-04 05:41
Okay I got it working OpenAI doesn't work, but claude works.
OpenAI handler location?
Also requesting slack would definitely love to contribute.
 
Working Version of Windows 11 WSL OpenDevin coming soon.

**Comment by rbren** [comment] 2024-04-04 13:49
Looks like it's time to fund your OpenAI account!

Closing this as it's not a bug with the project

**Closed by rbren** 2024-04-04 13:49 UTC
Labels: bug

**Comment by LewyCoda** [comment] 2024-04-04 16:42
As far as the OpenAI portion I can't use it :( 
When using it for a task it will sit idle and then spit out that. 
Almost like its request a bunch of API requests. - I would recommend looking at it if possible.
Either way claude is working so I'm happy.

**Comment by LewyCoda** [comment] 2024-04-05 01:55
**[Makefile]**
# Makefile for OpenDevin project

# Variables
DOCKER_IMAGE = ghcr.io/opendevin/sandbox
BACKEND_PORT = 3000
BACKEND_HOST = "127.0.0.1:$(BACKEND_PORT)"
FRONTEND_PORT = 3001
DEFAULT_WORKSPACE_DIR = "./workspace"
DEFAULT_MODEL = "gpt-4-0125-preview"
CONFIG_FILE = config.toml

# Build
build:
        @echo "Building project..."
        @echo "Pulling Docker image..."
        @docker pull $(DOCKER_IMAGE)
        @echo "Installing Python dependencies..."
        @python3 -m pip install pipenv
        @python3 -m pip install --upgrade pipenv
        @python3 -m pipenv install -v
        @echo "Setting up frontend environment..."
        @cd frontend && npm install

# Start backend
start-backend:
        @echo "Starting backend..."
        @python3 -m pipenv run uvicorn opendevin.server.listen:app --port $(BACKEND_PORT)

# Start frontend
start-frontend:
        @echo "Starting frontend..."
        @cd frontend && BACKEND_HOST=$(BACKEND_HOST) FRONTEND_PORT=$(FRONTEND_PORT) npm run start

# Run the app
run:
        @echo "Running the app..."
        @mkdir -p logs
        @rm -f logs/pipe
        @mkfifo logs/pipe
        @cat logs/pipe | (make start-backend) &
        @echo 'test' | tee logs/pipe | (make start-frontend)

# Setup config.toml
setup-config:
        @echo "Setting up config.toml..."
        @read -p "Enter your LLM Model name (see docs.litellm.ai/docs/providers for full list) [default: $(DEFAULT_MODEL)]: " llm_model; \
         llm_model=$${llm_model:-$(DEFAULT_MODEL)}; \
         echo "LLM_MODEL=\"$$llm_model\"" >> $(CONFIG_FILE).tmp

        @read -p "Enter your LLM API key: " llm_api_key; \
         echo "LLM_API_KEY=\"$$llm_api_key\"" >> $(CONFIG_FILE).tmp

        @read -p "Enter your workspace directory [default: $(DEFAULT_WORKSPACE_DIR)]: " workspace_dir; \
         workspace_dir=$${workspace_dir:-$(DEFAULT_WORKSPACE_DIR)}; \
         echo "WORKSPACE_DIR=\"$$workspace_dir\"" >> $(CONFIG_FILE).tmp

        @mv $(CONFIG_FILE).tmp $(CONFIG_FILE)

# Help
help:
        @echo "Usage: make [target]"
        @echo "Targets:"
        @echo "  build               - Build project, including environment setup and dependencies."
        @echo "  start-backend       - Start the backend server for the OpenDevin project."
        @echo "  start-frontend      - Start the frontend server for the OpenDevin project."
        @echo "  run                 - Run the OpenDevin application, starting both backend and frontend servers."
        @echo "                        Backend Log file will be stored in the 'logs' directory."
        @echo "  setup-config        - Setup the configuration for OpenDevin by providing LLM API key, LLM Model name, and workspace directory."
        @echo "  help                - Display this help message, providing information on available targets."

# Phony targets
.PHONY: install start-backend start-frontend run setup-config help


For now this is the only way

**Comment by LewyCoda** [comment] 2024-04-05 03:27
poetry update broke the installer :(

**Comment by rbren** [comment] 2024-04-05 03:35
@LewyCoda can you say more about what's broken, or open a new issue? It's working better for most people now.

CC @dorbanianas

**Comment by LewyCoda** [comment] 2024-04-05 04:05
All lived in harmony until the poetry nation attacked!
All good trying on ubuntu now

**Comment by dorbanianas** [comment] 2024-04-05 08:08
@LewyCoda can pls explain more if help is needed because I'm using also wsl 2 with windows 11

**Comment by nickjuntilla** [comment] 2024-06-03 18:28
I pay and it still gets the quota error.
