### ISSUE TITLE
[Bug]: OpenDevin hangs/time when requiring interactive inputs (Yes/No)

### ISSUE THREAD

**Issue by xingyaoww** [OpenDevin/OpenDevin#3030] opened 2024-07-19 15:38 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

OpenDevin currently hangs when prompted to provide yes/no like this:
```
The authenticity of host '[github.com](http://github.com/) (140.82.113.4)' can't be established.

ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.

This key is not known by any other names

Are you sure you want to continue connecting (yes/no/[fingerprint])?
```

This is primarily due to our current `pexcept` parsing logic in `Runtime` (e.g., in `pxssh`) does not consider these scenario and will not look for pattern like `yes/no` and hand it over to the agent.

### Current OpenDevin version

```bash
main
```

### Installation and Configuration

```bash
docker
```

**Comment by mamoodi** [comment] 2024-07-19 16:50
Good idea creating a mega issue because there are multiple issues with this. Are you thinking of keeping all the issues open though? Or closing them as a duplicate of the mega issue?

**Comment by SmartManoj** [comment] 2024-07-27 07:37
Duplicate of #892

**Comment by tobitege** [comment] 2024-07-27 07:39
Yes, lets close this one as it is part of the "mega" issue already.

**Closed by tobitege** 2024-07-27 07:39 UTC
Labels: bug, severity:medium
