### ISSUE TITLE
We need LM STUDIO Support

### ISSUE THREAD

**Issue by SupercaliG** [OpenDevin/OpenDevin#2415] opened 2024-06-13 14:39 UTC
I believe LM Studio would be a great addition to OpenDevin. I feel this is a gray area currently which I'm sure is being worked on in the background. Hopefully some good documentation on how to get it working will come out with the release of the next updates. It would be nice to be able to utilize more powerful LLMs on smaller machines.

**Comment by mamoodi** [comment] 2024-07-07 17:10
This may be a duplicate of documenting LM studio support: https://github.com/OpenDevin/OpenDevin/issues/419

**Comment by mamoodi** [comment] 2024-07-10 19:23
Going to close this as a duplicate of the issue I mentioned above which has a lot of discussion on it already.

**Closed by mamoodi** 2024-07-10 19:23 UTC
Labels: enhancement
