### ISSUE TITLE
[Bug]: OpenDevin Local Hosting app.py issues

### ISSUE THREAD

**Issue by Faultyskullslayer** [OpenDevin/OpenDevin#2797] opened 2024-07-04 19:05 UTC
### Is there an existing issue for the same bug?

- [x] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Hello everyone,

When I use OpenDevin to build a sample website on windows
![OpenDev](https://github.com/OpenDevin/OpenDevin/assets/119021962/a088851c-17b9-487a-aed4-610b3978038b)
, I ask it to create a basic site with a calculator. OpenDevin successfully builds the app.py file, codes it, and creates the templates folder along with the index file. However, when I attempt to host it, the hosting appears successful according to the server log, which states:

* Serving Flask app 'calculator_app'
* Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
* Running on http://127.0.0.1:5000
Press CTRL+C to quit
The browser agent then tries to access the local URL to test it. Despite the server log showing the server is running and other commands (like searching Google) working fine, it never manages to load the locally hosted page. I'm always met with an error (see attached image).

I've also tried using VMware with Ubuntu Linux to run a fresh, clean environment, following all the proper setup steps (or so I think). Yet, I encounter the same issue: everything works except when it tries to load the locally hosted page.

Perhaps I'm using it in a way that wasn't intended? I'm new to this kind of stuff, so forgive my ignorance if I'm misunderstanding how to run it properly. I feel like the solution might be something simple that I'm overlooking.

Thank you!

### Current OpenDevin version

```bash
I think ghcr.io/opendevin/opendevin:0.7  I could be wrong should be the latest version though thats how i download it at least.
```

### Installation and Configuration

```bash
The way I set it up (could be wrong) 
I have my folder Devin 
and then 
This is what I run in PowerShell 

cd "C:\Users\Work Account\Desktop\Devin"

git clone https://github.com/OpenDevin/OpenDevin.git

cd "C:\Users\Work Account\Desktop\Devin\OpenDevin"


$WORKSPACE_BASE = "$pwd\workspace"

docker run -it `
    --pull always `
    -e SANDBOX_USER_ID=1000 `
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE `
    -v ${WORKSPACE_BASE}:/opt/workspace_base `
    -v /var/run/docker.sock:/var/run/docker.sock `
    -p 3000:3000 `
    --add-host host.docker.internal:host-gateway `
    --name "opendevin-app-$(Get-Date -Format 'yyyyMMddHHmmss')" `
    ghcr.io/opendevin/opendevin:0.7

Here is what that output looks like 

0.7: Pulling from opendevin/opendevin
Digest: sha256:fa41135b3800d07b7bb7850c072914580a0107cee706f8bfe1b3691b7b7eaaad
Status: Image is up to date for ghcr.io/opendevin/opendevin:0.7
Starting OpenDevin...
Setting up enduser with id 1000
Docker socket group id: 0
root:x:0:
Group with id 0 already exists
Running as enduser
/app/.venv/lib/python3.12/site-packages/llama_index_client/types/metadata_filter.py:20: SyntaxWarning: invalid escape sequence '\*'
  """
18:55:23 - opendevin:INFO: listen.py:100 - File upload config: max_size=0MB, restrict_types=False, allowed_extensions=['.*']
INFO:     Started server process [36]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3000 (Press CTRL+C to quit)
INFO:     ('172.17.0.1', 57166) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiI4MTRhZjAwMS02YWQ1LTQwOTItYWZhYy0wMjlkZWFmZGQzNWMifQ.Lset5TawYTJF9EsreL4_x28VW94bixxKv8FpikmcE_Q&latest_event_id=55" [accepted]
18:55:30 - opendevin:ERROR: auth.py:29 - Invalid token
INFO:     connection open
INFO:     connection closed
INFO:     ('172.17.0.1', 59406) - "WebSocket /ws" [accepted]
INFO:     connection open
18:55:33 - opendevin:INFO: agent.py:64 - Using server runtime
18:55:33 - opendevin:INFO: ssh_box.py:202 - SSHBox is running as opendevin user with USER_ID=1000 in the sandbox
18:55:33 - opendevin:INFO: ssh_box.py:247 - Detected initial session.
18:55:33 - opendevin:INFO: ssh_box.py:249 - Creating new Docker container
18:55:33 - opendevin:WARNING: ssh_box.py:715 - Using port forwarding till the enable host network mode of Docker is out of experimental mode.Check the 897th issue on https://github.com/OpenDevin/OpenDevin/issues/ for more information.
18:55:33 - opendevin:INFO: ssh_box.py:688 - Mounting workspace directory: C:\Users\Work Account\workspace
18:55:33 - opendevin:INFO: ssh_box.py:723 - Mounting volumes: {'C:\\Users\\Work Account\\workspace': {'bind': '/workspace', 'mode': 'rw'}, '/tmp/cache': {'bind': '/home/opendevin/.cache', 'mode': 'rw'}}
18:55:33 - opendevin:INFO: ssh_box.py:688 - Mounting workspace directory: C:\Users\Work Account\workspace
18:55:36 - opendevin:INFO: ssh_box.py:734 - Container started
18:55:37 - opendevin:INFO: ssh_box.py:750 - waiting for container to start: 1, container status: running
18:55:37 - opendevin:INFO: ssh_box.py:409 - Connecting to SSH session...
18:55:37 - opendevin:INFO: ssh_box.py:411 - You can debug the SSH connection by running: `ssh -v -p 45395 opendevin@host.docker.internal` using the password 'b0d4d4c6-f299-4f47-85b2-5a26bf60f088'
18:55:38 - opendevin:INFO: ssh_box.py:415 - Connected to SSH session
18:55:39 - opendevin:INFO: agent.py:96 - Creating agent CodeActAgent using LLM claude-3-haiku-20240307
18:55:39 - opendevin:INFO: llm.py:122 - Initializing LLM with model: claude-3-haiku-20240307
18:55:39 - opendevin:INFO: mixin.py:41 - Initializing plugins in the sandbox
18:55:39 - opendevin:INFO: mixin.py:28 - Sourced /opendevin/bash.bashrc and ~/.bashrc successfully
18:55:39 - opendevin:INFO: mixin.py:54 - Copied files from [/app/opendevin/runtime/plugins/agent_skills] to [/opendevin/plugins/agent_skills] inside sandbox.
18:55:39 - opendevin:INFO: mixin.py:62 - Initializing plugin [agent_skills] by executing [/opendevin/plugins/agent_skills/setup.sh] in the sandbox.
18:55:41 - opendevin:INFO: mixin.py:79 - Plugin agent_skills initialized successfully
18:55:41 - opendevin:INFO: mixin.py:28 - Sourced /opendevin/bash.bashrc and ~/.bashrc successfully
18:55:41 - opendevin:INFO: mixin.py:54 - Copied files from [/app/opendevin/runtime/plugins/jupyter] to [/opendevin/plugins/jupyter] inside sandbox.
18:55:41 - opendevin:INFO: mixin.py:62 - Initializing plugin [jupyter] by executing [/opendevin/plugins/jupyter/setup.sh] in the sandbox.
18:55:43 - opendevin:INFO: mixin.py:79 - Plugin jupyter initialized successfully
18:55:43 - opendevin:INFO: mixin.py:28 - Sourced /opendevin/bash.bashrc and ~/.bashrc successfully
18:55:43 - opendevin:INFO: browser_env.py:68 - Starting browser env...
18:55:43 - opendevin:ERROR: state.py:64 - Failed to restore state from session: sessions/7ce52f56-5acc-4ef4-bb1e-dcd8ba6a52df/agent_state.pkl
Error restoring state sessions/7ce52f56-5acc-4ef4-bb1e-dcd8ba6a52df/agent_state.pkl
18:55:43 - opendevin:INFO: agent_controller.py:197 - [Agent Controller 7ce52f56-5acc-4ef4-bb1e-dcd8ba6a52df] Setting agent(CodeActAgent) state from AgentState.LOADING to AgentState.INIT
18:55:43 - opendevin:INFO: agent_controller.py:135 - [Agent Controller 7ce52f56-5acc-4ef4-bb1e-dcd8ba6a52df] Starting step loop...
18:55:50 - opendevin:INFO: browser_env.py:95 - Browser env started.
```

### Model and Agent

Usually This 

Model:
claude-3-haiku-20240307 (Mainly This one)

Or GPT4o

Agent:
CodeActAgent

### Operating System

WSL on Windows I think But I tried it on a Linux as well so even if I did the wsl part wrong I still got the same result. 
I'm also using a Alienware laptop M15 R7

### Reproduction Steps

Create OpenDevin like I did in the steps

Launch it input info for model and key

Ask it to build a website upon hosting it or asking it to use browser agent to then go to that page I get the error/issue. 

### Logs, Errors, Screenshots, and Additional Context

Just point me on where to go and I will respond with logs and errors that I come up with the logs are long or terminal output is.

**Comment by amosk** [comment] 2024-07-04 21:31
Same issue on Mac OS M1, v.7, Chat-GPT 4o, Docker Desktop with 26.1.4, Brave Browser w/ blockers off. 

![image](https://github.com/OpenDevin/OpenDevin/assets/318363/a9c2b27c-1f16-4681-b96d-14af7fc3e88b)


Here's a mix of OD's Terminal commands and some of mine. I was trying to find out why when I went to localhost:5000 in another tab it wouldn't load anything. Guess its sandboxed by Docker?

```
$ pip install flask openai
[Package installed successfully]

$ python3 app.py > server.log 2>&1 &
[1] 170
[1]+  Exit 1                  python3 app.py > server.log 2>&1

$ cat server.log
  File "/workspace/app.py", line 33
    prompt=f"Extract all URLs from the following HTML content:
           ^
SyntaxError: unterminated string literal (detected at line 33)

$ python3 app.py > server.log 2>&1 &
[1] 177

$ curl http://127.0.0.1:5000

        <form method="post">
            <textarea name="email_content" rows="10" cols="30"></textarea><br>
            <input type="submit" value="Extract URLs">
        </form>
        <h2>Extracted URLs:</h2>
        <ul>
            
        </ul>
    
$ mkdir StarPrices
$ cd StarPrices
$ mkdir templates static
touch app.py

$ python3 /workspace/StarPrices/app.py > /workspace/StarPrices/server.log 2>&1 &
[2] 198

$ cat /workspace/StarPrices/server.log
 * Serving Flask app 'app'
 * Debug mode: off
Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.
[2]+  Exit 1                  python3 /workspace/StarPrices/app.py > /workspace/StarPrices/server.log 2>&1

$ python3 /workspace/StarPrices/app.py > /workspace/StarPrices/server.log 2>&1 &
[2] 205

$ curl http://127.0.0.1:5001

        <form method="post">
            <textarea name="email_content" rows="10" cols="30"></textarea><br>
            <input type="submit" value="Extract URLs">
        </form>
        <h2>Extracted URLs:</h2>
        <ul>
            
        </ul>
    

$ ps -ef | grep app.py
opendev+   160    76  0 20:38 pts/0    00:00:00 grep app.py

$ ifconfig
-bash: ifconfig: command not found

$ netstat
-bash: netstat: command not found

$ ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 20:25 ?        00:00:00 sshd: /usr/sbin/sshd -D -p 37483
root        64     1  0 20:25 ?        00:00:00 sshd: opendevin [priv]
opendev+    75    64  0 20:25 ?        00:00:00 sshd: opendevin@pts/0
opendev+    76    75  0 20:25 pts/0    00:00:00 -bash
opendev+   112     1  0 20:25 pts/0    00:00:01 /opendevin/miniforge3/bin/python
opendev+   118     1  0 20:25 pts/0    00:00:01 /opendevin/miniforge3/bin/python
opendev+   125   112  0 20:25 ?        00:00:01 /opendevin/miniforge3/bin/python
root       152     0  0 20:35 pts/1    00:00:00 /bin/sh
opendev+   164    76  0 20:42 pts/0    00:00:00 ps -ef
```

**Comment by SmartManoj** [comment] 2024-07-06 12:14
Duplicate of https://github.com/OpenDevin/OpenDevin/issues/897#issuecomment-2185469797

**Closed** 2024-07-07 00:01 UTC
Labels: bug
