### ISSUE TITLE
Add to readme: do not use root

### ISSUE THREAD

**Issue by kroggen** [OpenDevin/OpenDevin#961] opened 2024-04-10 03:32 UTC
Add to somewhere on the readme that installation as `root` is not supported

**Comment by yufansong** [comment] 2024-04-10 06:40
What do you mean `installation as root is not supported `? You mean agent cannot run as root in sandbox or you cannot install opendevin as root? Can you elaborate more details?

**Comment by rbren** [comment] 2024-04-15 14:59
Going to close this one--not entirely clear what the issue is, and hopefully `docker run` makes it easier

**Closed by rbren** 2024-04-15 14:59 UTC
Labels: enhancement, severity:low

**Comment by kroggen** [comment] 2024-04-15 18:28
It is not possible to run OpenDevin as root.

Check #969 and #887
