### ISSUE TITLE
when Launching OpenDevin, popup in red, ERROR: WebSocket connection is not ready.

### ISSUE THREAD

**Issue by ivanjrt** [OpenDevin/OpenDevin#880] opened 2024-04-08 03:07 UTC
#### Describe the bug
Afer launching OpenDevin `make run` then I go to  http://localhost:3001/ then the second, it opens up I get the popup error message:  **ERROR: WebSocket connection is not ready.**
then the agent saying that will start after 10 seconds but never initializes.

#### Setup and configuration
**Current version**:

```bash
commit 6e3b554317de7bc5d96ef81b4097287e05c0c4d0 (HEAD -> main, origin/main, origin/HEAD)
Author: RaGe <foragerr@users.noreply.github.com>
Date:   Sun Apr 7 15:57:31 2024 -0400
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
LLM_API_KEY="lm-studio"
LLM_BASE_URL="http://localhost:1234/v1"
LLM_MODEL="openai/Mistral-7B-Instruct-v0.2-GGUF/mistral-7b-instruct-v0.2.Q6_K.gguf"
LLM_EMBEDDING_MODEL="local"
WORKSPACE_DIR="./workspace"
```

**My model and agent** (you can see these settings in the UI):
* Model: **LLM_MODEL="openai/Mistral-7B-Instruct-v0.2-GGUF/mistral-7b-instruct-v0.2.Q6_K.gguf"**
* Agent: NA, _does not load after 10 seconds_

**Commands I ran to install and run OpenDevin**:
```
make start-backend
make start-frontend
```

**Steps to Reproduce**:
1. I'm using Windows 11 > WSL
2. using Docker
![image](https://github.com/OpenDevin/OpenDevin/assets/44326428/cb5cb360-fcdc-43b0-8514-15fccc4afb65)
3. attempt to write the commands above, to launch OpenDevin

**Logs, error messages, and screenshots**:
![image](https://github.com/OpenDevin/OpenDevin/assets/44326428/3c120d7b-ae09-408c-9eb3-bf8290b84887)
Logs from `OpenDevin\logs` 

#### Additional Context
```
21:50:19 - opendevin:INFO: session.py:38 - WebSocket disconnected, sid: REDACTED-GUI
21:50:19 - opendevin:INFO: session.py:38 - WebSocket disconnected, sid: REDACTED-GUI
21:50:34 - opendevin:INFO: session.py:38 - WebSocket disconnected, sid: REDACTED-GUI
21:50:36 - opendevin:INFO: session.py:38 - WebSocket disconnected, sid: REDACTED-GUI
21:50:36 - opendevin:INFO: session.py:38 - WebSocket disconnected, sid: REDACTED-GUI
21:57:01 - opendevin:INFO: session.py:38 - WebSocket disconnected, sid: REDACTED-GUI
21:57:01 - opendevin:INFO: session.py:38 - WebSocket disconnected, sid: REDACTED-GUI
22:00:38 - opendevin:INFO: session.py:38 - WebSocket disconnected, sid: REDACTED-GUI
22:00:38 - opendevin:INFO: session.py:38 - WebSocket disconnected, sid: REDACTED-GUI
22:04:28 - opendevin:INFO: session.py:38 - WebSocket disconnected, sid: REDACTED-GUI
22:04:28 - opendevin:INFO: session.py:38 - WebSocket disconnected, sid: REDACTED-GUI
```

**Comment by zhonggegege** [comment] 2024-04-08 03:12
[https://github.com/OpenDevin/OpenDevin/issues/873#issue-2229887194](url)
It's the same problem as here, and I have the same problem. You can try `make run` again and it will start successfully, but you will still get stuck on the following problems.

**Comment by SmartManoj** [comment] 2024-04-08 04:00
wrong hyperlink

https://github.com/OpenDevin/OpenDevin/issues/873#issue-2229887194

**Comment by zhonggegege** [comment] 2024-04-09 08:21
logs----------------------------------------------
16:13:02 - opendevin:INFO: session.py:38 - WebSocket disconnected, sid: 4223ab84-bff9-4880-8af9-6db03910bfcd
16:13:02 - opendevin:INFO: session.py:38 - WebSocket disconnected, sid: 4223ab84-bff9-4880-8af9-6db03910bfcd

After git pull update, make run, or make start-backend, make start-frontend, this's still the case. It could occasionally run successfully before, but now it cannot reproduce the successful start after multiple attempts, and a red box prompt always pops up, websocket question.
![image](https://github.com/OpenDevin/OpenDevin/assets/152971528/727c3fd0-d50d-40f7-a310-c7c8c043491b)

**Comment by dorbanianas** [comment] 2024-04-09 15:33
Fixed by : https://github.com/OpenDevin/OpenDevin/pull/941 you can now pull the latest changes!

**Closed by dorbanianas** 2024-04-09 15:33 UTC
Labels: bug

**Comment by ivanjrt** [comment] 2024-04-10 02:37
Hi Dorbanianas,

I did a
```
git reset --hard HEAD
git clean -xffd
git pull
```
the message still pops-up 3 times now 😆 although it goes away before it used to stay up the whole time.
![image](https://github.com/OpenDevin/OpenDevin/assets/44326428/d488f075-f42c-4a9e-a6b0-8001ffc7b2e4)  <br/>
for good or worse now I get extra errors   <br/>
![image](https://github.com/OpenDevin/OpenDevin/assets/44326428/dd16f437-4c70-45ba-9b69-589263443af0)  <br/>
checked my docker and docker shows up that is running the image.  <br/>
![image](https://github.com/OpenDevin/OpenDevin/assets/44326428/1ba1adda-29bd-450c-98b0-37926a7ef84a) <br/>
then i decided to start all over again, so I deleted all the folder and started from scratch once again, but the issue is repeated exactly like before

**Comment by ivanjrt** [comment] 2024-04-10 03:00
adding this issue on issue #911

**Comment by dorbanianas** [comment] 2024-04-10 09:04
@ivanjrt thanks for your feedback currently we are working to resolve this issue
