### ISSUE TITLE
ExceptionPxssh: Could not establish connection to host, docker login

### ISSUE THREAD

**Issue by flavioTocca** [OpenDevin/OpenDevin#911] opened 2024-04-08 15:20 UTC
I pulled today's commits and I get this error, I can't write to the bot and the classic message from the bot doesn't appear

![fe](https://github.com/OpenDevin/OpenDevin/assets/64084046/6f36bdb0-75e7-417d-b7d8-a17eead8dfbf)

![controller](https://github.com/OpenDevin/OpenDevin/assets/64084046/0d008266-271b-46fb-a0d4-d77ba17df2b3)

**Comment by PierrunoYT** [comment] 2024-04-08 16:22
I have the same issue

**Comment by rbren** [comment] 2024-04-08 16:56
Thanks for the report @flavioTocca! We're looking into it.

@PierrunoYT if there's already an open issue, there's no need to open a second one--you can just add details to the existing issue.

**Comment by rbren** [comment] 2024-04-08 17:00
@flavioTocca are you on windows? Can you explain more about your setup? (In the future, it's very helpful if you fill out the bug template)

**Comment by xingyaoww** [comment] 2024-04-08 17:01
Can you also run `docker ps` to see if the container has been started? Also, can you try `ssh -v` following the warning message with the password to see what you get?

**Comment by PierrunoYT** [comment] 2024-04-08 17:02
I have the same issue as mentioned in the closed Issue

## Bug Description
An error occurs when trying to establish an SSH connection to the sandbox environment while running `make run`, preventing the creation of the AgentController.

## Setup and Configuration
**Current Version**:

```bash
01c4c4bee4b5d8dc227e3432f585229a7c9d7126 (HEAD -> main, origin/main, origin/HEAD)
Author: ITNerdAZ <158104716+ITNerdAZ@users.noreply.github.com>
Date:   Mon Apr 8 14:56:02 2024 +0000

    Add installation warning to readme (#883)

    * Update README

    * Update README.md

    ---------

    Co-authored-by: Robert Brennan <accounts@rbren.io>
```


**My config.toml and environment vars** (be sure to redact API keys):
```toml
LLM_MODEL="gpt-4-0125-preview"
LLM_API_KEY="XYZ"
WORKSPACE_DIR="./workspace"
```

**My model and agent** (you can see these settings in the UI):
* Model:
* Agent:

**Commands I ran to install and run OpenDevin**:
```
make run
```

## Steps to Reproduce
1. Clone the repository
2. Change into the project directory
3. Run `make run`

## Logs, Error Messages, and Screenshots
```
18:19:42 - opendevin:INFO: sandbox.py:210 - Connecting to opendevin@localhost via ssh. If you encounter any issues, you can try `ssh -v -p 2222 opendevin@localhost` with the password '9e5c46b1-856b-42f1-ac09-3240398b8d40' and report the issue on GitHub.
18:19:43 - opendevin:ERROR: manager.py:134 - Error creating controller.
Traceback (most recent call last):
  File "/mnt/c/Users/pierr/OpenDevin/opendevin/server/agent/manager.py", line 125, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/pierr/OpenDevin/opendevin/controller/agent_controller.py", line 86, in __init__
    self.command_manager = CommandManager(
                           ^^^^^^^^^^^^^^^
  File "/mnt/c/Users/pierr/OpenDevin/opendevin/controller/command_manager.py", line 14, in __init__
    self.shell = DockerInteractive(
                 ^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/pierr/OpenDevin/opendevin/sandbox/sandbox.py", line 139, in __init__
    self.start_ssh_session()
  File "/mnt/c/Users/pierr/OpenDevin/opendevin/sandbox/sandbox.py", line 213, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password, port=2222)
  File "/home/pierre/.cache/pypoetry/virtualenvs/opendevin-lPNnzAY--py3.12/lib/python3.12/site-packages/pexpect/pxssh.py", line 424, in login
    raise ExceptionPxssh('Could not establish connection to host')
pexpect.pxssh.ExceptionPxssh: Could not establish connection to host
```

## Additional Context
- The error occurs when running `make run`, which attempts to establish an SSH connection to `opendevin@localhost` on port 2222.
- The password for the SSH connection is provided in the log message: `9e5c46b1-856b-42f1-ac09-3240398b8d40`.
- The error is raised by the `pexpect.pxssh` library, indicating that it could not establish a connection to the host.
- The error propagates through the `DockerInteractive`, `CommandManager`, and `AgentController` classes, ultimately preventing the creation of the controller.
- The issue seems to be related to the SSH connection setup and configuration within the OpenDevin sandbox environment when running the application using `make run`.

**Comment by JustinLin610** [comment] 2024-04-08 17:06
could you please try `docker ps` and `docker stop <container_id>` and then rerun the project?

**Comment by flavioTocca** [comment] 2024-04-08 18:10
@rbren sorry for not being specific, yes I use windows 11, with wls 2 and ubunto, I am using a local model, which responded yesterday

**Comment by ac12aa** [comment] 2024-04-08 22:19
same issue

**Comment by enyst** [comment] 2024-04-08 22:29
@flavioTocca @ac12aa Can you try the commands in the comments above?
- ssh -v as said in the message from opendevin too; and tell what happens, do you get an error?
- docker stop <container_id> before trying again.

There have been fixes today, do also a ```git pull``` before, just in case.

**Comment by hcossio** [comment] 2024-04-08 23:28
@flavioTocca @ac12aa @PierrunoYT this was happening to me as well. I had used sudo for make run and apparently it caused the issue. I deleted the Docker containers and ran again without sudo and it worked correctly.

**Comment by Nastase** [comment] 2024-04-09 08:15
I'm having the same issue. Updated the code, ran `make build` again, deleted the docker container but still have the same issue. When running the suggested command, `ssh -v -p 2222 opendevin@localhost` I get a "connection refused"

Running on Windows 11 with WSL2.

Logs:

```shell
09:08:12 - opendevin:INFO: sandbox.py:210 - Connecting to opendevin@localhost via ssh. If you encounter any issues, you can try `ssh -v -p 2222 opendevin@localhost` with the password '7bee83ba-cb83-40d9-840d-0e5eda87f293' and report the issue on GitHub.
09:08:12 - opendevin:ERROR: manager.py:134 - Error creating controller.
Traceback (most recent call last):
  File "/home/nastase/developer/OpenDevin/opendevin/server/agent/manager.py", line 125, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/home/nastase/developer/OpenDevin/opendevin/controller/agent_controller.py", line 86, in __init__
    self.command_manager = CommandManager(
                           ^^^^^^^^^^^^^^^
  File "/home/nastase/developer/OpenDevin/opendevin/controller/command_manager.py", line 14, in __init__
    self.shell = DockerInteractive(
                 ^^^^^^^^^^^^^^^^^^
  File "/home/nastase/developer/OpenDevin/opendevin/sandbox/sandbox.py", line 139, in __init__
    self.start_ssh_session()
  File "/home/nastase/developer/OpenDevin/opendevin/sandbox/sandbox.py", line 213, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password, port=2222)
  File "/home/nastase/.cache/pypoetry/virtualenvs/opendevin-P5XeTA7Z-py3.11/lib/python3.11/site-packages/pexpect/pxssh.py", line 424, in login
    raise ExceptionPxssh('Could not establish connection to host')
pexpect.pxssh.ExceptionPxssh: Could not establish connection to host
```

**Comment by flavioTocca** [comment] 2024-04-09 08:52
@enyst I did git pull today but it still doesn't work, @hcossio I didn't launch it with the sudo command, but I tried it again it didn't work

**Comment by xingyaoww** [comment] 2024-04-09 09:30
It looks like the current implementation mainly causes issues for "Windows + WSL" users. I suspect the major cause may be related to network connectivity issues inside WSL (e.g., due to [proxy](https://github.com/OpenDevin/OpenDevin/issues/912#issuecomment-2044463156)).

I think a short-term quick fix to get the whole thing back to work would be to revert to the commit before the introduction of this bug (`git checkout 6e3b554317de7bc5d96ef81b4097287e05c0c4d`, then `make run`). We could also revert these changes, and work in a separate `dev` branch until we get docker-compose working as a whole. @rbren how do you think?

A more fundamental fix will be available once we can package the entire backend/frontend server inside a container (i.e., once we merge the docker-compose PRs: #377, #481), and use the docker network to isolate the potentially different host network environments.

**Comment by dorbanianas** [comment] 2024-04-09 16:22
@xingyaoww I'm using wsl and everything works fine! but maybe having a dev branch for the docker-compose would be a good idea

**Comment by jenkor** [comment] 2024-04-09 16:42
Same issue he
![image](https://github.com/OpenDevin/OpenDevin/assets/11050697/94cf0d2c-a22c-4372-b8fb-61ce3107252f)
re
![image](https://github.com/OpenDevin/OpenDevin/assets/11050697/836c6218-b6ca-4304-812d-d76703ecb336)

**Comment by PierrunoYT** [comment] 2024-04-09 16:48
Same here after pulling the latest commits.

![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/e270df5e-b6a2-4126-8d7b-88f588903c95)
![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/4c89bc02-3676-4131-988a-60ab9621caae)

**Comment by ivanjrt** [comment] 2024-04-10 02:59
+1 I have the very same issue 
![image](https://github.com/OpenDevin/OpenDevin/assets/44326428/b844a1b6-f96d-45e9-beb8-43e51bf5bb92)

**Comment by yimothysu** [comment] 2024-04-10 03:38
I'm getting the same error on Ubuntu (not Windows).

**Comment by yimothysu** [comment] 2024-04-10 03:52
`ssh -v -p 2222 opendevin@localhost` works within the container but throws "Connection refused" on the host.

**Comment by mrcashcash** [comment] 2024-04-10 05:34
same issue here windows+wsl.
container is up and running. 

> ssh -v -p 2222 opendevin@localhost works within the container but throws "Connection refused" on the host.

**Comment by Mass0090** [comment] 2024-04-10 09:32
I have the same issue, i have tried to fix it but still, i am using windows 11 and WSL Ubuntu. 

(base) malam@Mass:~/OpenDevin$ cd OpenDevin
(base) malam@Mass:~/OpenDevin/OpenDevin$ make run
Running the app...
Starting backend server...
Waiting for the backend to start...
/home/malam/.cache/pypoetry/virtualenvs/opendevin-VK4jyVz5-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_list" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/malam/.cache/pypoetry/virtualenvs/opendevin-VK4jyVz5-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_name" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/malam/.cache/pypoetry/virtualenvs/opendevin-VK4jyVz5-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_group_alias" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/malam/.cache/pypoetry/virtualenvs/opendevin-VK4jyVz5-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_info" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/malam/.cache/pypoetry/virtualenvs/opendevin-VK4jyVz5-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_id" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
INFO:     Started server process [64487]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
Backend started successfully.
Starting frontend with npm...

> opendevin-frontend@0.1.0 start
> vite --port 3001


  VITE v5.2.8  ready in 405 ms

  ➜  Local:   http://localhost:3001/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
INFO:     ('127.0.0.1', 50378) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiJlNDAxNjgxMS0xMTU5LTRkOTQtYmNmMy01OGVhMWE2YTcyNzQifQ.eyX_jlm1j5xK_ibJWPHYPdi4NasiCs8cPzRoo_tGQuU" [accepted]
Starting loop_recv for sid: e4016811-1159-4d94-bcf3-58ea1a6a7274
INFO:     connection open
INFO:     127.0.0.1:50390 - "GET /refresh-files HTTP/1.1" 200 OK
INFO:     127.0.0.1:50398 - "GET /messages/total HTTP/1.1" 200 OK
INFO:     127.0.0.1:50400 - "GET /configurations HTTP/1.1" 200 OK
INFO:     127.0.0.1:50408 - "GET /refresh-files HTTP/1.1" 200 OK
13:27:24 - opendevin:INFO: sandbox.py:135 - Using workspace directory: /home/malam/OpenDevin/OpenDevin/workspace
13:27:24 - opendevin:INFO: sandbox.py:324 - Container stopped
13:27:54 - opendevin:INFO: sandbox.py:356 - Container started
13:27:55 - opendevin:INFO: sandbox.py:373 - waiting for container to start: 1, container status: running
13:27:55 - opendevin:INFO: sandbox.py:212 - Connecting to opendevin@localhost via ssh. If you encounter any issues, you can try `ssh -v -p 2222 opendevin@localhost` with the password '7695e32d-e236-47b4-a0a3-2e1e3a6c446c' and report the issue on GitHub.
13:27:59 - opendevin:ERROR: agent.py:135 - Error creating controller: password refused
Traceback (most recent call last):
  File "/home/malam/OpenDevin/OpenDevin/opendevin/server/agent/agent.py", line 126, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/home/malam/OpenDevin/OpenDevin/opendevin/controller/agent_controller.py", line 88, in __init__
    self.command_manager = CommandManager(
                           ^^^^^^^^^^^^^^^
  File "/home/malam/OpenDevin/OpenDevin/opendevin/controller/command_manager.py", line 19, in __init__
    self.shell = DockerInteractive(
                 ^^^^^^^^^^^^^^^^^^
  File "/home/malam/OpenDevin/OpenDevin/opendevin/sandbox/sandbox.py", line 153, in __init__
    self.start_ssh_session()
  File "/home/malam/OpenDevin/OpenDevin/opendevin/sandbox/sandbox.py", line 217, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password,
  File "/home/malam/.cache/pypoetry/virtualenvs/opendevin-VK4jyVz5-py3.11/lib/python3.11/site-packages/pexpect/pxssh.py", line 440, in login
    raise ExceptionPxssh('password refused')
pexpect.pxssh.ExceptionPxssh: password refused
INFO:     127.0.0.1:50416 - "GET /messages HTTP/1.1" 200 OK
INFO:     127.0.0.1:38948 - "GET /litellm-models HTTP/1.1" 200 OK
INFO:     127.0.0.1:38956 - "GET /litellm-agents HTTP/1.1" 200 OK
INFO:     127.0.0.1:38960 - "GET /litellm-models HTTP/1.1" 200 OK
INFO:     127.0.0.1:38966 - "GET /litellm-agents HTTP/1.1" 200 OK
INFO:     127.0.0.1:59004 - "GET /litellm-models HTTP/1.1" 200 OK
INFO:     127.0.0.1:59006 - "GET /litellm-agents HTTP/1.1" 200 OK
INFO:     127.0.0.1:59008 - "GET /litellm-models HTTP/1.1" 200 OK
INFO:     127.0.0.1:59018 - "GET /litellm-agents HTTP/1.1" 200 OK
^CReceived signal 2, exiting...
INFO:     connection closed
ERROR:    Traceback (most recent call last):
  File "/home/malam/anaconda3/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/malam/anaconda3/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1511, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1504, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1377, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 555, in uvloop.loop.Loop._run
  File "uvloop/handles/poll.pyx", line 216, in uvloop.loop.__on_uvpoll_event
  File "uvloop/cbhandles.pyx", line 83, in uvloop.loop.Handle._run
  File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run
  File "uvloop/loop.pyx", line 397, in uvloop.loop.Loop._read_from_self
  File "uvloop/loop.pyx", line 402, in uvloop.loop.Loop._invoke_signals
  File "uvloop/loop.pyx", line 377, in uvloop.loop.Loop._ceval_process_signals
  File "/home/malam/OpenDevin/OpenDevin/opendevin/server/agent/manager.py", line 40, in handle_signal
    exit(0)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/malam/.cache/pypoetry/virtualenvs/opendevin-VK4jyVz5-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 741, in lifespan
    await receive()
  File "/home/malam/.cache/pypoetry/virtualenvs/opendevin-VK4jyVz5-py3.11/lib/python3.11/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/malam/anaconda3/lib/python3.11/asyncio/queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

make: *** [Makefile:129: run] Interrupt

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/malam/anaconda3/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/malam/anaconda3/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1511, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1504, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1377, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 555, in uvloop.loop.Loop._run
  File "uvloop/handles/poll.pyx", line 216, in uvloop.loop.__on_uvpoll_event
  File "uvloop/cbhandles.pyx", line 83, in uvloop.loop.Handle._run
  File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run
  File "uvloop/loop.pyx", line 397, in uvloop.loop.Loop._read_from_self
  File "uvloop/loop.pyx", line 402, in uvloop.loop.Loop._invoke_signals
  File "uvloop/loop.pyx", line 377, in uvloop.loop.Loop._ceval_process_signals
  File "/home/malam/OpenDevin/OpenDevin/opendevin/server/agent/manager.py", line 40, in handle_signal
    exit(0)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/malam/.cache/pypoetry/virtualenvs/opendevin-VK4jyVz5-py3.11/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 240, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/malam/.cache/pypoetry/virtualenvs/opendevin-VK4jyVz5-py3.11/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/malam/.cache/pypoetry/virtualenvs/opendevin-VK4jyVz5-py3.11/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/malam/.cache/pypoetry/virtualenvs/opendevin-VK4jyVz5-py3.11/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/malam/.cache/pypoetry/virtualenvs/opendevin-VK4jyVz5-py3.11/lib/python3.11/site-packages/starlette/middleware/errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "/home/malam/.cache/pypoetry/virtualenvs/opendevin-VK4jyVz5-py3.11/lib/python3.11/site-packages/starlette/middleware/cors.py", line 77, in __call__
    await self.app(scope, receive, send)
  File "/home/malam/.cache/pypoetry/virtualenvs/opendevin-VK4jyVz5-py3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/malam/.cache/pypoetry/virtualenvs/opendevin-VK4jyVz5-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/malam/.cache/pypoetry/virtualenvs/opendevin-VK4jyVz5-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/malam/.cache/pypoetry/virtualenvs/opendevin-VK4jyVz5-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/malam/.cache/pypoetry/virtualenvs/opendevin-VK4jyVz5-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 373, in handle
    await self.app(scope, receive, send)
  File "/home/malam/.cache/pypoetry/virtualenvs/opendevin-VK4jyVz5-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 96, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "/home/malam/.cache/pypoetry/virtualenvs/opendevin-VK4jyVz5-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/malam/.cache/pypoetry/virtualenvs/opendevin-VK4jyVz5-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 94, in app
    await func(session)
  File "/home/malam/.cache/pypoetry/virtualenvs/opendevin-VK4jyVz5-py3.11/lib/python3.11/site-packages/fastapi/routing.py", line 348, in app
    await dependant.call(**values)
  File "/home/malam/OpenDevin/OpenDevin/opendevin/server/listen.py", line 42, in websocket_endpoint
    await session_manager.loop_recv(sid, agent_manager.dispatch)
  File "/home/malam/OpenDevin/OpenDevin/opendevin/server/session/manager.py", line 36, in loop_recv
    await self._sessions[sid].loop_recv(dispatch)
  File "/home/malam/OpenDevin/OpenDevin/opendevin/server/session/session.py", line 29, in loop_recv
    data = await self.websocket.receive_json()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/malam/.cache/pypoetry/virtualenvs/opendevin-VK4jyVz5-py3.11/lib/python3.11/site-packages/starlette/websockets.py", line 157, in receive_json
    message = await self.receive()
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/malam/.cache/pypoetry/virtualenvs/opendevin-VK4jyVz5-py3.11/lib/python3.11/site-packages/starlette/websockets.py", line 49, in receive
    message = await self._receive()
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/malam/.cache/pypoetry/virtualenvs/opendevin-VK4jyVz5-py3.11/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 379, in asgi_receive
    data = await self.recv()
           ^^^^^^^^^^^^^^^^^
  File "/home/malam/.cache/pypoetry/virtualenvs/opendevin-VK4jyVz5-py3.11/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await asyncio.wait(
  File "/home/malam/anaconda3/lib/python3.11/asyncio/tasks.py", line 428, in wait
    return await _wait(fs, timeout, return_when, loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/malam/anaconda3/lib/python3.11/asyncio/tasks.py", line 535, in _wait
    await waiter
asyncio.exceptions.CancelledError
(base) malam@Mass:~/OpenDevin/OpenDevin$ docker ps
CONTAINER ID   IMAGE                       COMMAND                  CREATED              STATUS              PORTS     NAMES
c51a0cd3a809   ghcr.io/opendevin/sandbox   "/usr/sbin/sshd -D -…"   About a minute ago   Up About a minute             sandbox-e4016811-1159-4d94-bcf3-58ea1a6a7274
(base) malam@Mass:~/OpenDevin/OpenDevin$ 

![image](https://github.com/OpenDevin/OpenDevin/assets/166603966/a37f7b04-ab76-4577-9b20-0d40a8392198)

![image](https://github.com/OpenDevin/OpenDevin/assets/166603966/896927ce-7142-42d2-aafc-b1dec9a45350)

**Comment by PierrunoYT** [comment] 2024-04-10 12:00
Is this fixed?

**Comment by azmodeuz** [comment] 2024-04-10 12:13
guess it could be a good opportunity to try SWE-Agent. lol

**Comment by jenkor** [comment] 2024-04-10 16:08
> Is this fixed?

windows10+WSL Ubuntu nope

**Comment by jenkor** [comment] 2024-04-10 19:45
> Yes, this issue has been resolved for me. The steps are as follows:
> 
> 1. I uninstalled WSL and deleted all the OpenDevin files.
> 2. I reinstalled WSL and downloaded OpenDevin files to WSL directly.
> 3. I made sure all requirements are ready and the correct versions are as mentioned in the tutorials (Python >= 3.11, NodeJS >= 18.17.1, Poetry >= 1.8).
> 
> For Docker, I didn't download a desktop. I used Linux commands to download it and encountered some permission issues. With the help of ChatGPT, I solved it and obtained the permissions.
> 
> You have to make sure to download everything in the WSL and forget about Windows.
> 
> I followed the steps (make build) and encountered some errors like the package not being complete for Python pip and apt. I downloaded it so make build could download all the files, and then I made setup-config and make run. I didn't have any issues with Docker or any SSH problems.
> 
> I am currently facing a loop issue, which I believe can be resolved by upgrading ChatGPT3.5 to ChatGPT4.
> 
> You need to install everything in WSL, including Node and Python, and ensure all requirements are met with the correct versions as mentioned. For Docker, you don't have to download Docker desktop as I downloaded it inside WSL, and it is running perfectly without any issues.
> 
> I am not a programmer or developer so excuse me with my short knowledge, with all respect for the developers.
> 
> if you can help me with the loop issue, i will send the issue in the right error page as i followed all the steps but still i am facing Error during task loop. ile "/home/malam/.cache/pypoetry/virtualenvs/opendevin-8jU3_nnO-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 8526, in exception_type raise e File "/home/malam/.cache/pypoetry/virtualenvs/opendevin-8jU3_nnO-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 7367, in exception_type raise RateLimitError( litellm.exceptions.RateLimitError: OpenAIException - Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Mate you are life saver!

I didn't have to delete local files that reside on windows but it did stop Desktop Docker and installed it directly on WSL.
I works now!

Thank you again!

**Comment by PierrunoYT** [comment] 2024-04-10 20:06
> > Yes, this issue has been resolved for me. The steps are as follows:
> 
> > 
> 
> > 1. I uninstalled WSL and deleted all the OpenDevin files.
> 
> > 2. I reinstalled WSL and downloaded OpenDevin files to WSL directly.
> 
> > 3. I made sure all requirements are ready and the correct versions are as mentioned in the tutorials (Python >= 3.11, NodeJS >= 18.17.1, Poetry >= 1.8).
> 
> > 
> 
> > For Docker, I didn't download a desktop. I used Linux commands to download it and encountered some permission issues. With the help of ChatGPT, I solved it and obtained the permissions.
> 
> > 
> 
> > You have to make sure to download everything in the WSL and forget about Windows.
> 
> > 
> 
> > I followed the steps (make build) and encountered some errors like the package not being complete for Python pip and apt. I downloaded it so make build could download all the files, and then I made setup-config and make run. I didn't have any issues with Docker or any SSH problems.
> 
> > 
> 
> > I am currently facing a loop issue, which I believe can be resolved by upgrading ChatGPT3.5 to ChatGPT4.
> 
> > 
> 
> > You need to install everything in WSL, including Node and Python, and ensure all requirements are met with the correct versions as mentioned. For Docker, you don't have to download Docker desktop as I downloaded it inside WSL, and it is running perfectly without any issues.
> 
> > 
> 
> > I am not a programmer or developer so excuse me with my short knowledge, with all respect for the developers.
> 
> > 
> 
> > if you can help me with the loop issue, i will send the issue in the right error page as i followed all the steps but still i am facing Error during task loop. ile "/home/malam/.cache/pypoetry/virtualenvs/opendevin-8jU3_nnO-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 8526, in exception_type raise e File "/home/malam/.cache/pypoetry/virtualenvs/opendevin-8jU3_nnO-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 7367, in exception_type raise RateLimitError( litellm.exceptions.RateLimitError: OpenAIException - Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
> 
> 
> 
> Mate you are life saver!
> 
> 
> 
> I didn't have to delete local files that reside on windows but it did stop Desktop Docker and installed it directly on WSL.
> 
> I works now!
> 
> 
> 
> Thank you again!

I use Docker inside WSL but I have Docker also on Desktop for other Projects.

**Comment by rbren** [comment] 2024-04-10 21:41
Hey all--we just merged a possible fix. Try adding `SANDBOX_TYPE=exec` to your config.toml

**Comment by tobitege** [comment] 2024-04-10 21:41
I didn't uninstall anything, but installed Docker (dockerd) into WSL2 itself and run it in one terminal (and do not start Docker Desktop on Windows).
Then in 2nd terminal run make build and make run again and when it's done, opened OD on my Windows browser and it works! 
Thanks to @Mass0090 for those invaluable hints!! 👍

**Comment by Mass0090** [comment] 2024-04-10 23:48
@jenkor  & @tobitege  , I'm glad to know that it works for you.

@PierrunoYT , I'm really not sure if Docker desktop is the main reason, but you can follow @rbren  steps and let us know if it works.

**Comment by ivanjrt** [comment] 2024-04-11 04:04
> Hey all--we just merged a possible fix. Try adding `SANDBOX_TYPE=exec` to your config.toml

i did this but then I got me an error which it I couldn't even open the webapp :(
![image](https://github.com/OpenDevin/OpenDevin/assets/44326428/66727517-a68b-4440-8be3-c790935ab42f)

**Comment by ivanjrt** [comment] 2024-04-11 04:07
then I install Docker inside of the WSL and stoped it from running in Windows, then make sure the app was running within the wsl, and same error 
![image](https://github.com/OpenDevin/OpenDevin/assets/44326428/2afe326d-7e04-4ef9-ab97-c76c749ad07c)

i'd wonder what is in the docker image, is there a way to port it out?

**Comment by flavioTocca** [comment] 2024-04-11 10:12
hello @rbren putting SANDBOX_TYPE=exec in the toml I receive the same error as @ivanjrt  but if I change the config.py file in the server folder then it is successful receiving responses from the local model even if with other problems but I think it is another issue with some JSON problems
![configpy](https://github.com/OpenDevin/OpenDevin/assets/64084046/45a03768-7f1e-44de-a342-898653b4312f)
![other](https://github.com/OpenDevin/OpenDevin/assets/64084046/19b84eed-fbec-4501-8a52-2fafc2237ee5)

**Closed** 2024-04-11 14:39 UTC
Labels: bug, severity:critical
