### ISSUE TITLE
Make the agent error message more informative

### ISSUE THREAD

**Issue by chunhualiao** [OpenDevin/OpenDevin#2450] opened 2024-06-15 17:26 UTC
**What problem or use case are you trying to solve?**

I have tried OpenDevin for a few tasks. I have encountered a few times the error message "Agent encountered an error."  or "Agent encountered an unexpected error." 

It took me a while to figure out how I could dig into docker logs to find out more. 

**Describe the UX of the solution you'd like**

It would be helpful to directly display the error messages extracted from the relevant docker log. 

**Do you have thoughts on the technical implementation?**

The user interface could have a new tab called agent error message to display docker log, after the tabs for Editor, Browser, Jupyter.

**Comment by mamoodi** [comment] 2024-07-01 16:08
Duplicate of https://github.com/OpenDevin/OpenDevin/issues/1451

**Closed by mamoodi** 2024-07-01 16:08 UTC
Labels: enhancement
