### ISSUE TITLE
Remove LangChain and LlamaIndex dependency

### ISSUE THREAD

**Issue by casper-hansen** [OpenDevin/OpenDevin#387] opened 2024-03-30 11:58 UTC
**What problem or use case are you trying to solve?**

LangChain and LlamaIndex are large dependencies that requires additional dependencies. To attract more developers and to simplify development, OpenDevin should reduce external dependencies.

**Do you have thoughts on the technical implementation?**

Reimplement the specific functionality from both packages in OpenDevin. It is likely that the specific functionality used can be replaced by a few hundred lines of code.

**Comment by rbren** [comment] 2024-03-30 14:41
LangChain is really close to being removed. We just need to redo the templates here: https://github.com/OpenDevin/OpenDevin/blob/main/agenthub/langchains_agent/utils/prompts.py

Would happily accept a PR there.

LlamaIndex is a little harder. I think we need an in-memory Vector database for long-term memory retrieval (though the current agent doesn't really utilize it). Not sure we want to implement embeddings/indexing/searching etc ourselves, but maybe there's something lighter weight than llamaindex. Maybe we can get away with raw chromadb?

**Comment by SuibhneOFoighil** [comment] 2024-03-31 23:37
Removed Langchain from [above file](https://github.com/OpenDevin/OpenDevin/blob/main/agenthub/langchains_agent/utils/prompts.py). Made PR [here](https://github.com/OpenDevin/OpenDevin/pull/474). Can work on removing llamaIndex next .

**Comment by casper-hansen** [comment] 2024-04-01 09:56
Excellent work @SuibhneOFoighil

**Comment by rbren** [comment] 2024-04-01 14:30
I also have https://github.com/OpenDevin/OpenDevin/pull/402 which renames to MonologueAgent

**Comment by omutist** [comment] 2024-04-01 16:55
@rbren 
JFYI: dev_config/python/mypy.ini mentions langchain_agent path
`exclude = agenthub/langchains_agent/regression`

**Comment by rbren** [comment] 2024-04-01 17:32
Thanks! Fix: https://github.com/OpenDevin/OpenDevin/pull/513

**Comment by rbren** [comment] 2024-04-01 17:33
To update this thread: lanchain is now removed, llamaindex is still a dependency

**Comment by emrgnt-cmplxty** [comment] 2024-04-01 18:46
[R2R is a very streamlined](https://github.com/SciPhi-AI/R2R) framework that is focusing on just deploying a RAG backend. 

In one of my previous projects I spent some time thinking about symbol-based semantic [code search over a graph](https://github.com/emrgnt-cmplxty/automata/blob/full-automata/automata/symbol/graph/symbol_graph.py).

If we were to re-implement this inside of R2R, would Devin consider using R2R as a RAG backend?

**Comment by rbren** [comment] 2024-04-02 02:52
I think the best options are:
* llama-index (since it's the best-known RAG tool, does RAG very well out of the box, and is full of features)
* raw vector database (which gives us more control)

Eventually we're going to want a _really_ flexible RAG solution that agents can take advantage of without too much fuss. So I'm really leaning towards keeping LlamaIndex

**Comment by rbren** [comment] 2024-04-05 18:29
Going to close this one for now. Worth having a long-term discussion here, maybe in Slack

**Closed by rbren** 2024-04-05 18:29 UTC
Labels: enhancement
