### ISSUE TITLE
Document difference between different agents

### ISSUE THREAD

**Issue by shaggy2626** [OpenDevin/OpenDevin#1984] opened 2024-05-23 01:22 UTC
Its my first time using the project, can you tell me which agent I should be using as default and when would I use the other agents? I'm not sure how it works, are there any docs?

![image](https://github.com/OpenDevin/OpenDevin/assets/120447538/7448350c-6750-45d7-a3fe-888f85a46d93)

**Comment by enyst** [comment] 2024-05-23 11:52
CodeActAgent is the default agent and it's the best for any coding tasks.

We are just deprecating SWEAgent since CodeAct now basically includes the commands it had. Monologue and Planner might be useful for testing particular stuff (Monologue has long term memory, Planner is an experiment in, well, planning). A large number of the rest are microagents, suitable for a very particular task (e.g. CommitWriterAgent for writing the commit message of a single commit).

In general, it's unlikely you need the specialized ones. The default should just work for particular tasks too.

**Comment by ramsey-coding** [comment] 2024-05-23 15:12
@enyst what is the main benefit of using the CodeAct agent? Does it have any unique features that make it better than the SWE-agent?

**Comment by mamoodi** [comment] 2024-06-08 18:50
Going to close this as a duplicate of this newer one which will be used as a catch all for this particular issue going forward https://github.com/OpenDevin/OpenDevin/issues/2251.

**Closed by mamoodi** 2024-06-08 18:50 UTC
Labels: question
