### ISSUE TITLE
[Bug]: GitHub allows merge even if integration tests are failing

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#1801] opened 2024-05-15 03:14 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Dunno what the issue is here...
<img width="824" alt="Screenshot 2024-05-14 at 11 13 58 PM" src="https://github.com/OpenDevin/OpenDevin/assets/7611973/ef6ee970-26ca-4053-ad16-6ab69fe2ee9d">

### Current Version

```bash
N/A
```

### Installation and Configuration

```bash
N/A
```

**Comment by mamoodi** [comment] 2024-06-08 18:24
@rbren is this still an issue?

**Comment by mamoodi** [comment] 2024-07-06 16:20
@rbren any follow up to this?

**Comment by SmartManoj** [comment] 2024-07-09 11:50
@enyst Were any of the two PRs not up-to-date with the main branch when merged?

**Comment by rbren** [comment] 2024-07-10 20:30
I haven't been merging PRs for a bit, so I'm not sure if it's still an issue. Feel free to close!

**Comment by tobitege** [comment] 2024-07-10 20:59
I think the issue is not/no longer existing. Lets close this for now.

**Closed by tobitege** 2024-07-10 20:59 UTC
Labels: bug, severity:medium, small effort
