### ISSUE TITLE
AgentThinkAction.__init__() got an unexpected keyword argument 'summary'

### ISSUE THREAD

**Issue by JackieQi** [OpenDevin/OpenDevin#1002] opened 2024-04-10 21:47 UTC
#### Describe the bug
When running devin with ollama/mistral:v0.2. After first prompt "Hello".  I got this error at step 11.
```
TypeError: AgentThinkAction.__init__() got an unexpected keyword argument 'summary'
```

#### Setup and configuration
**Current version**:

```
commit 9846e242994a9a88786f8bdba525e080d70ae072 (HEAD -> main, origin/main, origin/HEAD)
Author: Robert Brennan <accounts@rbren.io>
Date:   Wed Apr 10 14:48:40 2024 -0500

    Fix logger import (#985)

    * fix logger import
    * fix mypy version
    * make mypy happy (#994)

    ---------

    Co-authored-by: Engel Nyst <enyst@users.noreply.github.com>
```

**My config.toml and environment vars** (be sure to redact API keys):
```
LLM_MODEL="ollama/mistral:v0.2"
LLM_API_KEY="ollama"
LLM_EMBEDDING_MODEL="local"
LLM_BASE_URL="http://localhost:11434"
WORKSPACE_DIR="./workspace"

```

**My model and agent** (you can see these settings in the UI):
* Model: ollama/mistral:v0.2
* Agent:

**Commands I ran to install and run OpenDevin**:
```
git pull 
conda create -n testdevin python=3.11
make build
make setup-config
make run
```

**Steps to Reproduce**:
1. open devin (localhost:3001)
2. Use prompt "Hello"
3. At step 11 it threw an error

**Logs, error messages, and screenshots**:
<img width="989" alt="Screenshot 2024-04-10 at 2 42 57 PM" src="https://github.com/OpenDevin/OpenDevin/assets/358367/515a9b4e-7660-42b2-b6a1-89d2893f66b5">

<img width="501" alt="Screenshot 2024-04-10 at 2 43 22 PM" src="https://github.com/OpenDevin/OpenDevin/assets/358367/dd0500da-c3e9-4f6a-ad8f-9229042368e5">

<img width="501" alt="Screenshot 2024-04-10 at 2 43 31 PM" src="https://github.com/OpenDevin/OpenDevin/assets/358367/3134457f-1c53-407c-a803-7fb57282269c">

#### Additional Context
```

==============
STEP 0

PLAN:
hello

ACTION:
CmdRunAction(command='ls', background=False, action=<ActionType.RUN: 'run'>)

OBSERVATION:



==============
STEP 1

PLAN:
hello

ACTION:
AgentThinkAction(thought="Based on the output of 'ls', it looks like there's a file named `hello.py` here. Let me try to run that.", action=<ActionType.THINK: 'think'>)


==============
STEP 2

PLAN:
hello

ACTION:
AgentThinkAction(thought="Let's check if the `hello.py` file contains the code to produce a 'Hello, World!' output.", action=<ActionType.THINK: 'think'>)


==============
STEP 3

PLAN:
hello

ACTION:
FileReadAction(path='hello.py', action=<ActionType.READ: 'read'>)

ERROR:
[Errno 2] No such file or directory: 'workspace/hello.py'
Traceback (most recent call last):
  File "/Users/jackie/Projects/AI/OpenDevin/opendevin/controller/agent_controller.py", line 173, in step
    if inspect.isawaitable(action.run(self)):
                           ^^^^^^^^^^^^^^^^
  File "/Users/jackie/Projects/AI/OpenDevin/opendevin/action/fileop.py", line 27, in run
    with open(path, "r", encoding="utf-8") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'workspace/hello.py'

OBSERVATION:
[Errno 2] No such file or directory: 'workspace/hello.py'


==============
STEP 4

PLAN:
hello

ACTION:
AgentThinkAction(thought="It looks like there's no `hello.py` file here after all. Maybe I should check if that file exists in the first place, before coming to this workspace.", action=<ActionType.THINK: 'think'>)


==============
STEP 5

PLAN:
hello

ACTION:
AgentRecallAction(query='Is there a `hello.py` file in the original directory?', action=<ActionType.RECALL: 'recall'>)

OBSERVATION:
Recalling memories...


==============
STEP 6

PLAN:
hello

ACTION:
AgentRecallAction(query='Is there a `hello.py` file in the original directory?', action=<ActionType.RECALL: 'recall'>)

OBSERVATION:
Recalling memories...


==============
STEP 7

PLAN:
hello

ACTION:
AgentThinkAction(thought="Let me check if there's a `hello.py` file in the original directory using the command line.", action=<ActionType.THINK: 'think'>)


==============
STEP 8

PLAN:
hello

ACTION:
AgentThinkAction(thought="Let's use the command line to check if there's a `hello.py` file in the original directory.", action=<ActionType.THINK: 'think'>)


==============
STEP 9

PLAN:
hello

ACTION:
AgentRecallAction(query='Does the original directory contain a `hello.py` file?', action=<ActionType.RECALL: 'recall'>)

OBSERVATION:
Recalling memories...


==============
STEP 10

PLAN:
hello

ACTION:
CmdRunAction(command="find /original_directory_path -name 'hello.py'", background=False, action=<ActionType.RUN: 'run'>)

OBSERVATION:
find: '/original_directory_path': No such file or directory


```

**Comment by rbren** [comment] 2024-04-10 22:21
Effectively a dupe of https://github.com/OpenDevin/OpenDevin/issues/1000

The agent returned an invalid action, which is semi-expected, but we failed hard instead of passing the error back to the LLM

Fix is incoming!

**Closed by rbren** 2024-04-10 22:21 UTC
Labels: bug
