### ISSUE TITLE
[Bug]: workspace vs workspace_base issue?

### ISSUE THREAD

**Issue by williambarberjr** [OpenDevin/OpenDevin#1659] opened 2024-05-08 20:49 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

When the codeact agent tries to write jupyter code and runs it, I get the error: `bash: line 1: /workspace/.tmp/.ipython_execution_tmp.py: No such file or directory`

When I look at the "code editor" tab, the .tmp/.ipython_execution_tmp.py is there but under workspace_base
![image](https://github.com/OpenDevin/OpenDevin/assets/9202147/6d43c2ae-17fe-439a-8cc3-07ccff8e12f0)

My guess is that's the issue?

### Current Version

```bash
opendevin:0.5
```

### Installation and Configuration

```bash
Doesn't seem to matter how I run it but this is my current starting command:
export LLM_API_KEY="..."
export LLM_MODEL="..."
export LLM_BASE_URL="..."
export WORKSPACE_BASE=$(pwd)/open_devin_test

sudo docker run \
    -e LLM_API_KEY \
    -e LLM_MODEL \
    -e LLM_BASE_URL \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -e SANDBOX_TYPE=exec \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    ghcr.io/opendevin/opendevin:0.5

I'm running this within wsl2 on windows
```

### Model and Agent

Behavior doesn't vary by model, have only ever tried it with the code act agent

### Reproduction Steps

1. Launch open devin
2. Prompt it to write python code
3. Get error

### Logs, Errors, Screenshots, and Additional Context

<img width="293" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/9202147/2b6b4f66-9f44-4d3c-bff5-109d5259d52a">

**Comment by rbren** [comment] 2024-05-10 02:24
@williambarberjr what do you get if you run `ls -lah $(pwd)/open_devin_test`

**Comment by umbes18** [comment] 2024-05-10 14:10
any solution?

**Comment by SmartManoj** [comment] 2024-05-10 14:29
`export WORKSPACE_BASE=$(pwd)/workspace`

**Comment by SmartManoj** [comment] 2024-05-10 15:19
![image](https://github.com/OpenDevin/OpenDevin/assets/7231077/1e83bf78-141d-4dd1-9854-29424b1c4830)
but no files in the container.

**Comment by SmartManoj** [comment] 2024-05-10 15:46
![image](https://github.com/OpenDevin/OpenDevin/assets/7231077/5f408fd7-253c-4652-bbdc-73be11628b63)
seems the sandbox is not restarting?

**Comment by umbes18** [comment] 2024-05-10 16:04
<img width="813" alt="Screenshot 2024-05-10 alle 18 02 04" src="https://github.com/OpenDevin/OpenDevin/assets/86656919/dd423fb2-51f6-469e-8f66-e99978bee237">
<img width="823" alt="Screenshot 2024-05-10 alle 18 02 11" src="https://github.com/OpenDevin/OpenDevin/assets/86656919/c0f8ed76-dec5-4a74-a086-e4b940700be4">

i have always these problem 

I'm running this on Mac m1 
`export WORKSPACE_BASE=$(pwd)/workspace;

docker run \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    ghcr.io/opendevin/opendevin:0.5`

**Comment by williambarberjr** [comment] 2024-05-10 18:05
> @williambarberjr what do you get if you run `ls -lah $(pwd)/open_devin_test`

```
ls -lah $(pwd)/open_devin_test
total 12K
drwxr-xr-x  3 myusername myusername 4.0K May 10 13:58 .
drwxr-x--- 27 myusername myusername 4.0K May 10 14:03 ..
drwxr-xr-x  2 myusername           42421 4.0K May  8 15:25 .tmp
```

Tried to replicate the error I was getting earlier this week and now I'm getting:
```
==============
STEP 0

18:01:34 - PLAN
run hello world in the ipython notebook
18:01:37 - ACTION
**IPythonRunCellAction**
THOUGHT:Sure, let's run a simple "Hello World!" in the IPython notebook environment:
CODE:
print("Hello World!")
18:01:37 - OBSERVATION
IPythonRunCellObservation(content='bash: line 1: /workspace/.tmp/.ipython_execution_tmp.py: No such file or directory', code='print("Hello World!")', observation='run_ipython')


==============
STEP 1

18:01:40 - ACTION
**IPythonRunCellAction**
THOUGHT:It seems there was an issue with the execution environment. Let me try running the "Hello World!" command again for you.
CODE:
print("Hello World!")
18:01:40 - OBSERVATION
IPythonRunCellObservation(content='bash: line 1: /workspace/.tmp/.ipython_execution_tmp.py: No such file or directory', code='print("Hello World!")', observation='run_ipython')


==============
STEP 2

18:01:46 - ACTION
It appears there is a persistent issue with the IPython notebook execution environment. Unfortunately, I can't directly resolve this environment setup issue from here. However, you can try running the Python code locally on your machine or in any online Python compiler. Here's the code you would use:

```python
print("Hello World!")
```

You can simply copy this into your Python environment and run it to see the output. If you have any other questions or need further assistance with a different task, feel free to ask!
18:01:46 - opendevin:INFO: agent_controller.py:201 - Setting agent state from AgentState.RUNNING to AgentState.AWAITING_USER_INPUT
```

When I go to docker desktop, click the vertical ... and "open in terminal" then poked around with these commands and results:
```
# pwd
/workspace
# ls
open_devin_test
# cd ..
# ls
bin  boot  dev  etc  home  lib  lib32  lib64  libx32  media  mnt  opendevin  opt  proc  root  run  sbin  srv  sys  tmp  usr  var  workspace
# cd opt 
# ls
# pwd
/opt
#
```

In other words, when looking inside the docker container for the sandbox, I don't see any subfolders inside `/opt`, so I'm not sure how it's supposed to handle the volume mapping requested with this -v flag: `-v $WORKSPACE_BASE:/opt/workspace_base`

**Comment by SmartManoj** [comment] 2024-05-11 02:13
@rbren Shouldn't `open_devin_test` folder be mapped to `/workspace` in sandbox?

@williambarberjr  What happens if you set `export WORKSPACE_BASE=$(pwd)/workspace;`?

**Comment by SmartManoj** [comment] 2024-05-11 12:01
@williambarberjr Could you check the main version?

**Comment by williambarberjr** [comment] 2024-05-12 00:52
> @williambarberjr What happens if you set `export WORKSPACE_BASE=$(pwd)/workspace;`?

If I understand what the -v volume flag is doing in the docker run command, I believe doing that would just try to map a) the result of concatenating my current working directory with /workspace (a directory which doesn't exist on my local machine) to b) /opt/workspace_base within the docker container (which also doesn't exist within the docker container)

So I don't think that will solve anything unless I'm missing something...

**Comment by SmartManoj** [comment] 2024-05-12 05:56
How did  `open_devin_test` folder come inside the workspace directory?
is that a nested folder?
![image](https://github.com/OpenDevin/OpenDevin/assets/7231077/455277f0-64f2-4880-afbc-d6e3375b9120)

**Comment by SmartManoj** [comment] 2024-05-12 13:42
> a directory which doesn't exist on my local machine

The following line will automatically create it.
https://github.com/OpenDevin/OpenDevin/blob/8bfae8413e74e1b6095d5380a7ea93b6b73a4537/containers/app/Dockerfile#L42

Duplicate of #1366

**Comment by rbren** [comment] 2024-05-14 17:51
I'm going to dedupe this with https://github.com/OpenDevin/OpenDevin/issues/1366

This is weird stuff, it seems to only pop up for a few folks. I will put more info in #1366 if anyone is able to help debug further

**Closed by rbren** 2024-05-14 17:51 UTC
Labels: bug
