### ISSUE TITLE
AgentManager is overwriting config.toml information

### ISSUE THREAD

**Issue by arya1105** [OpenDevin/OpenDevin#841] opened 2024-04-07 03:39 UTC
#### Describe the bug
The config.toml values seem to get overwritten when dispatching agents in recent code updates. 
I am trying to use one of the ollama models. But the code keeps reverting back to gpt 3.5 model and throws api_key error.

#### Setup and configuration
**Current version**:
Full code configured as per recommendations. 

Happens in class AgentManager:
```python
       directory = DEFAULT_WORKSPACE_DIR
        # if start_event and "directory" in start_event["args"]:
        #     directory = start_event["args"]["directory"]
        agent_cls = "MonologueAgent"
        if start_event and "agent_cls" in start_event["args"]:
            agent_cls = start_event["args"]["agent_cls"]
        model = LLM_MODEL
        # if start_event and "model" in start_event["args"]:
        #     model = start_event["args"]["model"]
        api_key = DEFAULT_API_KEY
        # if start_event and "api_key" in start_event["args"]:
        #     api_key = start_event["args"]["api_key"]
        api_base = DEFAULT_BASE_URL
        # if start_event and "api_base" in start_event["args"]:
        #     api_base = start_event["args"]["api_base"]

```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
LLM_API_KEY="ollama"
LLM_MODEL="ollama/mistral:7b"
LLM_EMBEDDING_MODEL="local"
LLM_BASE_URL="http://localhost:11434"
WORKSPACE_DIR="G:/Project/AI/Code/Workspaces/OpenDevin"
```

**My model and agent** (you can see these settings in the UI):
* Model:Mistral7B
* Agent:Monologue

**Commands I ran to install and run OpenDevin**:
```

```

**Steps to Reproduce**:
1. Update your config.toml 
2. Run opendevin backend using make start-backend
3. send a query to the agent.

**Logs, error messages, and screenshots**:

**Comment by lowlyocean** [comment] 2024-04-07 03:52
Looks like same thing I'm experiencing https://github.com/OpenDevin/OpenDevin/issues/793#issuecomment-2041298929

**Comment by enyst** [comment] 2024-04-07 03:56
Sorry for the frustration and thank you for the report. Yes, this is a regression and at the moment local models, and not only, don't work. It's being fixed though. I will close this issue since we have https://github.com/OpenDevin/OpenDevin/issues/793 , to keep information in one place.

**Closed by enyst** 2024-04-07 03:56 UTC
Labels: bug

**Comment by flavioTocca** [comment] 2024-04-07 08:26
prova a cambiare il file come nella risposta segnata qui #843
