### ISSUE TITLE
Bug on Windows

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#142] opened 2024-03-25 16:43 UTC
I runned this but it did not worked.

## Step 1: Set up the OpenAI API key

1. Sign in to OpenAI or create an account at https://openai.com/
2. Navigate to https://platform.openai.com/account/api-keys
3. Click "Create new secret key"
4. Copy the generated API key

## Step 2: Create a project folder

1. Create a new folder for your OpenDevin project, e.g., `C:\opendevin`

## Step 3: Create a virtual environment

1. Open the Windows command prompt (cmd.exe)
2. Navigate to your project folder: `cd C:\opendevin`
3. Create a new virtual environment with venv: `python -m venv env`

## Step 4: Activate the virtual environment

1. Activate the virtual environment: `env\Scripts\activate`

## Step 5: Set environment variables

1. Set the OPENAI_API_KEY environment variable: `set OPENAI_API_KEY=your_api_key_here`
2. Set the WORKSPACE_DIR environment variable: `set WORKSPACE_DIR=C:\opendevin`

## Step 6: Install dependencies

1. Install the Python dependencies: `python -m pip install -r requirements.txt`

## Step 7: Start the backend

1. Start the OpenDevin backend: `uvicorn opendevin.server.listen:app --port 3000`

## Step 8: Start the frontend (new terminal)

1. Open a new command prompt
2. Navigate to the frontend folder: `cd C:\opendevin\frontend`
3. Install the Node.js dependencies: `npm install`
4. Start the frontend: `npm run start -- --port 3001`

You can now access OpenDevin at http://localhost:3001 in your browser.

Remember to deactivate the virtual environment when you're done by typing `deactivate` in the command prompt.

**Comment by PierrunoYT** [comment] 2024-03-25 17:22
Can I contact you somehow?

**Comment by ha-zhcool** [comment] 2024-03-25 17:56
There is an issue with the tag of the docker image. The script is looking for the :latest image while it's not labeled as is on docker hub.
To fix the issue, you just have to point the script to the correct image.

1. Open file opendevin/sandbox/sandbox.py
2. locate the image name "opendevin/sandbox:latest"
3. replace with "opendevin/sandbox:v0.1"
4. restart the backend.

**Comment by PierrunoYT** [comment] 2024-03-25 18:05
> There is an issue with the tag of the docker image. The script is looking for the :latest image while it's not labeled as is on docker hub. To fix the issue, you just have to point the script to the correct image.
> 
>     1. Open file opendevin/sandbox/sandbox.py
> 
>     2. locate the image name "opendevin/sandbox:latest"
> 
>     3. replace with "opendevin/sandbox:v0.1"
> 
>     4. restart the backend.

The readme is missing content because there is nothing written that you need to use Docker

**Comment by ha-zhcool** [comment] 2024-03-25 19:25
> > There is an issue with the tag of the docker image. The script is looking for the :latest image while it's not labeled as is on docker hub. To fix the issue, you just have to point the script to the correct image.
> > ```
> > 1. Open file opendevin/sandbox/sandbox.py
> > 
> > 2. locate the image name "opendevin/sandbox:latest"
> > 
> > 3. replace with "opendevin/sandbox:v0.1"
> > 
> > 4. restart the backend.
> > ```
> 
> The readme is missing content because there is nothing written that you need to use Docker

I'm just a standard user of the project that faced the same issue and willing to help

**Comment by PierrunoYT** [comment] 2024-03-25 19:30
> > > There is an issue with the tag of the docker image. The script is looking for the :latest image while it's not labeled as is on docker hub. To fix the issue, you just have to point the script to the correct image.
> > > ```
> > > 1. Open file opendevin/sandbox/sandbox.py
> > > 
> > > 2. locate the image name "opendevin/sandbox:latest"
> > > 
> > > 3. replace with "opendevin/sandbox:v0.1"
> > > 
> > > 4. restart the backend.
> > > ```
> > 
> > 
> > The readme is missing content because there is nothing written that you need to use Docker
> 
> I'm just a standard user of the project that faced the same issue and willing to help

Ah okay I got it. Thank you.

**Comment by PierrunoYT** [comment] 2024-03-25 20:22
> What exactly do you mean with "did not work"? Which step didn't work? Did you get any error message?

Can I make a Discord Server for it?

**Comment by gujian2git** [comment] 2024-03-26 06:24
uvicorn opendevin.server.listen:app --port 3000
Traceback (most recent call last):
  File "D:\AppData\Program\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\AppData\Program\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\AppData\Program\anaconda3\Scripts\uvicorn.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\AppData\Program\anaconda3\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "D:\AppData\Program\anaconda3\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "D:\AppData\Program\anaconda3\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\AppData\Program\anaconda3\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "D:\AppData\Program\anaconda3\lib\site-packages\uvicorn\main.py", line 409, in main
    run(
  File "D:\AppData\Program\anaconda3\lib\site-packages\uvicorn\main.py", line 575, in run
    server.run()
  File "D:\AppData\Program\anaconda3\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\AppData\Program\anaconda3\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\AppData\Program\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\AppData\Program\anaconda3\lib\site-packages\uvicorn\server.py", line 69, in serve
    await self._serve(sockets)
  File "D:\AppData\Program\anaconda3\lib\site-packages\uvicorn\server.py", line 76, in _serve
    config.load()
  File "D:\AppData\Program\anaconda3\lib\site-packages\uvicorn\config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
  File "D:\AppData\Program\anaconda3\lib\site-packages\uvicorn\importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "D:\AppData\Program\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\Admin\ForWork\2024\MyCode\Python\FromGit\OpenDevin\opendevin\server\listen.py", line 1, in <module>
    from opendevin.server.session import Session
  File "D:\Admin\ForWork\2024\MyCode\Python\FromGit\OpenDevin\opendevin\server\session.py", line 8, in <module>
    from opendevin.controller import AgentController
  File "D:\Admin\ForWork\2024\MyCode\Python\FromGit\OpenDevin\opendevin\controller\__init__.py", line 19, in <module>
    from .command_manager import CommandManager
  File "D:\Admin\ForWork\2024\MyCode\Python\FromGit\OpenDevin\opendevin\controller\command_manager.py", line 4, in <module>
    from opendevin.sandbox.sandbox import DockerInteractive
  File "D:\Admin\ForWork\2024\MyCode\Python\FromGit\OpenDevin\opendevin\sandbox\sandbox.py", line 16, in <module>
    class DockerInteractive:
  File "D:\Admin\ForWork\2024\MyCode\Python\FromGit\OpenDevin\opendevin\sandbox\sandbox.py", line 20, in DockerInteractive
    workspace_dir: str | None = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by enyst** [comment] 2024-03-26 10:13
>workspace_dir: str | None = None,
>TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

What version of python are you using? This syntax has been introduced in 3.10. https://docs.python.org/3/whatsnew/3.10.html

**Comment by rbren** [comment] 2024-03-26 11:50
Looks like we've documented the need for latest python and for docker. Going to close this one, but let us know if you need more help!

**Closed by rbren** 2024-03-26 11:50 UTC
Labels: bug

**Comment by gujian2git** [comment] 2024-03-28 07:04
> > workspace_dir: str | None = None,
> > TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
> 
> What version of python are you using? This syntax has been introduced in 3.10. https://docs.python.org/3/whatsnew/3.10.html

Python version 3.12.2，I have changed Python version to 3.10，the exception still exists;

**Comment by rbren** [comment] 2024-03-28 14:40
Hrmm. That error message is almost always an indication of an old python version. I wonder if uvicorn is using an old version of python somewhere on your machine?

What does `uvicorn --version` show?

**Comment by rbren** [comment] 2024-03-28 15:02
Very strange. I'm totally unable to reproduce. Granted I'm on Linux, but it shouldn't really matter--it's a python typing error.

```bash
❯ /home/rbren/.asdf/installs/python/3.10.11/bin/uvicorn --version
Running uvicorn 0.29.0 with CPython 3.10.11 on Linux

❯ /home/rbren/.asdf/installs/python/3.10.11/bin/uvicorn opendevin.server.listen:app --port 3000
INFO:     Started server process [2153603]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
```

Everything I'm seeing online is cases of "I thought it was running python 3.10, but it turned out it was linking into an old version".

Maybe try reinstalling python, uvicorn, or `pip install --upgrade --force-reinstall -r requirements.txt`.

**Comment by abdullah-az** [comment] 2024-11-20 22:55
(env) PS C:\opendevin> python -m pip install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
