### ISSUE TITLE
[Bug]: Receive "Unexpected Application Error!" on localhost:3000

### ISSUE THREAD

**Issue by 4tal** [OpenDevin/OpenDevin#2108] opened 2024-05-28 12:40 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

When running docker using:
ghcr.io/opendevin/opendevin:main

around 2 days it stops working and when I enter localhost:3000 I'm getting the following
![image](https://github.com/OpenDevin/OpenDevin/assets/6404507/b419547f-eb27-45a2-bb99-fdf01a29380f)

Here's devtools:
![image](https://github.com/OpenDevin/OpenDevin/assets/6404507/39ba2241-ad04-4a27-b2a8-ae14ca05f838)

and terminal logs:
<img width="646" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/6404507/30474750-074e-40f5-b48b-97be98c7816a">

I'm using MacOs with M1

### Current OpenDevin version

```bash
main on commit 9434bcce4880dda390209633dc5cb307c2b499d8
```

### Installation and Configuration

```bash
export WORKSPACE_BASE=$(pwd)
export LLM_API_KEY="OPEN_AI_API_KEY"
    
docker run \
        -it \
        --pull=always \
        -e LLM_API_KEY \
        -e SANDBOX_TYPE=exec \
        -e SANDBOX_USER_ID=$(id -u) \
        -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
        -e HF_HOME=~/code/self/.cache \
        -v $WORKSPACE_BASE:/opt/workspace_base \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -p 3000:3000 \
        --add-host host.docker.internal:host-gateway \
        ghcr.io/opendevin/opendevin:main



When I'm switching to 0.5 it works fine.
```

### Model and Agent

default

### Operating System

Macos

### Reproduction Steps

Just run it on the commit I specified.

### Logs, Errors, Screenshots, and Additional Context

around 2 days it stops working and when I enter localhost:3000 I'm getting the following
![image](https://github.com/OpenDevin/OpenDevin/assets/6404507/b419547f-eb27-45a2-bb99-fdf01a29380f)

Here's devtools:
![image](https://github.com/OpenDevin/OpenDevin/assets/6404507/39ba2241-ad04-4a27-b2a8-ae14ca05f838)

and terminal logs:
<img width="646" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/6404507/30474750-074e-40f5-b48b-97be98c7816a">

**Comment by SmartManoj** [comment] 2024-05-28 12:45
Duplicate of #2087

**Closed by SmartManoj** 2024-05-28 12:45 UTC
Labels: bug

**Comment by 4tal** [comment] 2024-06-04 14:16
It works; it's probably some browser's cache issue.
