### ISSUE TITLE
Unable to Launch Terminal Emulator After Installing Dependencies

### ISSUE THREAD

**Issue by anouarop** [OpenDevin/OpenDevin#1059] opened 2024-04-12 18:39 UTC
Description:
I'm encountering an issue where I'm unable to launch any terminal emulator after installing various dependencies and tools on my system. Here's a summary of the steps I've taken and the details of the issue:

Steps Taken:
1. Installed dependencies using the following commands:
   - Installed nvm: 
     ```
     curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
     ```
   - Installed Node.js version 20:
     ```
     nvm install 20
     ```
   - Installed Poetry:
     ```
     curl -sSL https://install.python-poetry.org | python3 -
     ```
   - Cloned the OpenDevin repository:
     ```
     git clone https://github.com/OpenDevin/OpenDevin.git
     ```
   - Installed Make:
     ```
     apt install make
     ```
2. Ran various `make` commands as part of the setup process:
   ```
   make build
   make setup-config
   make start-frontend
   make start-backend
   ```

Issue Details:
- After installing the dependencies and running the setup commands, I'm unable to launch any terminal emulator (e.g., Terminator, GNOME Terminal).
- There are no error messages or warnings displayed when attempting to launch the terminal emulator.
- I've verified that there are no terminal processes already running in the background.
- Resetting the terminal emulator settings to default did not resolve the issue.
- Graphics drivers are up to date, and there are no resource constraints on the system.
- Rebooting the system did not resolve the issue.

Additional Information:
- Operating System: Ubuntu 22.04
- Dependencies Installed: nvm, Node.js version 20, Poetry, Make
- Application: Terminal emulator (e.g., Terminator, GNOME Terminal)

Any assistance in troubleshooting and resolving this issue would be greatly appreciated. If you need any further information or logs, please let me know. Thank you!

**Comment by anouarop** [comment] 2024-04-12 19:07
Hi there,

I realized I forgot to mention some additional steps I took regarding Python upgrades, which might be relevant to the issue:

I checked Python versions and added an additional repository to download Python 3.11:

sudo add-apt-repository ppa:deadsnakes/ppa

I updated the package lists and upgraded the system:

sudo apt update
sudo apt upgrade

Then, I installed Python 3.11:

sudo apt-get install python3.11

After that, I configured Python 3.11 as the default version:

sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1
sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 2
sudo update-alternatives --config python3

Choose option 2 for Python 3.11.

Finally, I installed the Python compatibility package:

sudo apt install python-is-python3

I suspect that these Python upgrades might be related to the issue I'm facing with the terminal emulator not launching. Any insights or suggestions would be appreciated.

Thanks!

**Comment by yufansong** [comment] 2024-04-13 00:33
Do you have any logs of the following cmd? If not, it is hard to help you. 
```
make build
make setup-config
make start-frontend
make start-backend
```

**Comment by anouarop** [comment] 2024-04-13 00:51
Problem solved.
When attempting to manage Python versions on Ubuntu, encountered difficulties setting Python 3.11 as the default version.


### Solution:
Resolved the Python version selection issue by running the following command:
```bash
sudo update-alternatives --config python3

and selecting option number 0, which sets mode auto .

**Comment by enyst** [comment] 2024-04-13 19:29
@anouarop I'm going to close this issue, since your last post says the problem is solved. But if it didn't actually solve the original problem, let us know.

**Closed by enyst** 2024-04-13 19:29 UTC
