### ISSUE TITLE
Not able to commit and push

### ISSUE THREAD

**Issue by AbhisekOmkar** [OpenDevin/OpenDevin#70] opened 2024-03-20 18:01 UTC
While pushing the code from vs code I'm getting the below error 

<img width="1420" alt="Screenshot 2024-03-20 at 11 30 21 PM" src="https://github.com/OpenDevin/OpenDevin/assets/67184718/d4c4872e-51e8-4501-b882-6655ae2ede77">
<img width="1440" alt="Screenshot 2024-03-20 at 11 29 54 PM" src="https://github.com/OpenDevin/OpenDevin/assets/67184718/0a363f94-849e-49ff-aaf6-95dcbbf4d14e">

**Comment by AbhisekOmkar** [comment] 2024-03-20 18:02
@neubig can u please help me out

**Comment by KShivendu** [comment] 2024-03-20 21:13
Please use [nvm](https://github.com/nvm-sh/nvm).

**Comment by xcodebuild** [comment] 2024-03-21 06:41
This is not a bug. The action triggered by commit in vscode does not use the node version switched by nvm in the vscode terminal.
A viable approach is to commit code in the terminal using command line. If you want to use the nvm version when committing code in the vscode GUI, please refer to https://stackoverflow.com/questions/44700432/visual-studio-code-to-use-node-version-specified-by-nvm.

**Comment by JustinLin610** [comment] 2024-03-21 07:06
Yeah this is not related to this repo. I think xcodebuild explained it. I'll just give a tag and close it. If you find it related to this project you can reopen it.

**Closed by JustinLin610** 2024-03-21 07:06 UTC
Labels: bug
