### ISSUE TITLE
I cannot make build, root permission for fedora 39

### ISSUE THREAD

**Issue by ayazwx** [OpenDevin/OpenDevin#734] opened 2024-04-04 21:49 UTC
**Commands I ran to install and run OpenDevin**:
```
make build
```
**I am getting permission error**:
```
npm ERR! code EACCES
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/corepack
npm ERR! dest /usr/local/lib/node_modules/.corepack-xqcTrkeV
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/corepack' -> '/usr/local/lib/node_modules/.corepack-xqcTrkeV'
npm ERR!  [Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/corepack' -> '/usr/local/lib/node_modules/.corepack-xqcTrkeV'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rename',
npm ERR!   path: '/usr/local/lib/node_modules/corepack',
npm ERR!   dest: '/usr/local/lib/node_modules/.corepack-xqcTrkeV'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in: /home/fedora/.npm/_logs/2024-04-04T21_43_35_334Z-debug-0.log
make: *** [Makefile:24: build] Error 243

```

**Then I try to run with root**:
```
sudo make build
```
```
Building project...
Pulling Docker image...
Using default tag: latest
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
make: *** [Makefile:16: build] Error 1
```

**Comment by dorbanianas** [comment] 2024-04-05 00:31
Try to use the pull the new changes and let me know if you faced any issues

**Comment by yufansong** [comment] 2024-04-05 20:21
Do you launch your local docker? If docker not running, it will report this error. You can try following cmd to see whether it works.
```
docker pull ghcr.io/opendevin/sandbox
```

Or try `docker ps`. If it is wrong, it is largely you own environment problem.

Seems not a bug related to opendevin. Close it now. If new error happeneds, feel free reopen it or open a new issue.

**Closed by yufansong** 2024-04-05 20:21 UTC
Labels: bug

**Comment by yufansong** [comment] 2024-04-05 20:22
Also see [here](https://github.com/OpenDevin/OpenDevin/issues/728#issuecomment-2038013327) for some previous solution.
