### ISSUE TITLE
make run result

### ISSUE THREAD

**Issue by shanghailiwei** [OpenDevin/OpenDevin#626] opened 2024-04-03 02:28 UTC
VITE v5.2.7  ready in 316 ms

  ➜  Local:   http://localhost:3001/
  ➜  Network: use --host to expose
INFO:     Started server process [81742]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
INFO:     ('127.0.0.1', 51589) - "WebSocket /ws" [accepted]
INFO:     connection open
INFO:     127.0.0.1:51590 - "GET /litellm-models HTTP/1.1" 200 OK
INFO:     127.0.0.1:51591 - "GET /litellm-agents HTTP/1.1" 200 OK
INFO:     127.0.0.1:51592 - "GET /litellm-models HTTP/1.1" 200 OK
INFO:     127.0.0.1:51593 - "GET /litellm-agents HTTP/1.1" 200 OK
Please check Docker is running using `docker ps`.
Error! Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
Failed to stop container: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
Error creating controller.
Please check Docker is running using `docker ps`.
Error! Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
Failed to stop container: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
Error creating controller.

**Comment by yimothysu** [comment] 2024-04-03 02:33
@shanghailiwei what is the output of `docker ps`?

**Comment by shanghailiwei** [comment] 2024-04-03 03:51
no docker running , what's the start command for docker ?

**Comment by shanghailiwei** [comment] 2024-04-03 04:59
(OpenDevin) (base) liwei@LiWei-MBP OpenDevin % python opendevin/sandbox/sandbox.py -d workspace 
Please check Docker is running using `docker ps`.
Error! Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
Failed to stop container: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
Failed to start Docker container: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

**Comment by ryanzh98** [comment] 2024-04-03 05:02
Having the same issue with ubuntu, here is what I did to resolve it.

s```
udo service docker start
sudo groupadd docker
whoami (get your username)
sudo usermod -aG docker YOUR_USERNAME
exit terminal and reopen it
rerun the backend
```

**Comment by shanghailiwei** [comment] 2024-04-03 05:41
> Having the same issue with ubuntu, here is what I did to resolve it.ubuntu 也有同样的问题，我是这样解决的。
> 
> ```
> sudo service docker start
> sudo groupadd docker
> whoami (get your username)
> sudo usermod -aG docker YOUR_USERNAME
> exit terminal and reopen it
> rerun the backend
> ```

谢谢兄弟,我是 Mac 系统, docker 服务是好的, 应该是在 make run 的时候,没有把 docker 启动起来.

**Comment by shanghailiwei** [comment] 2024-04-03 05:56
mkdir workspace
python3 opendevin/sandbox/sandbox.py -d workspace

Please check Docker is running using `docker ps`.
Error! Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
Failed to stop container: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
Failed to start Docker container: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

Mac system.

**Comment by shanghailiwei** [comment] 2024-04-03 15:14
finally I found the reason rely in the docker service which has warning event.

**Comment by enyst** [comment] 2024-04-03 22:07
> finally I found the reason rely in the docker service which has warning event.

Is it fixed now for you?

On Mac, I think you can also install Docker Desktop and start it.

**Comment by yufansong** [comment] 2024-04-05 21:19
A mac docker problem. Not a bug. Seems solved.

**Closed by yufansong** 2024-04-05 21:19 UTC
Labels: bug
