### ISSUE TITLE
[Bug]: Docker build fails when loading Monologue agent

### ISSUE THREAD

**Issue by edwardbrazier** [OpenDevin/OpenDevin#2362] opened 2024-06-10 09:49 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Ran the following command to build the docker:
docker buildx build -f containers/app/Dockerfile -t opendevin .

It ran the build process for a while and then failed.

### Current OpenDevin version

```bash
Cloned the Git repo on 09/06/2024.
```

### Installation and Configuration

```bash
See attachment.
```
<img width="452" alt="docker build failed" src="https://github.com/OpenDevin/OpenDevin/assets/90482370/76b6ef92-779d-4f37-8af6-739d7ed03edb">

### Model and Agent

N/A -- didn't run the application

### Operating System

WSL2 on Windows 10

### Reproduction Steps

1. Clone Git repo.
2. CD into the repo
3. docker buildx build -f containers/app/Dockerfile -t opendevin .

### Logs, Errors, Screenshots, and Additional Context

The line that failed was RUN python opendevin/core/download.py

See screenshot attached above.

### Attempts to rectify
After this problem, I commented out a couple of lines as below and tried again. The build completed.
<img width="334" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/90482370/3fa90b4d-ed2f-4596-94f2-18fc8a5f18c9">

**Comment by edwardbrazier** [comment] 2024-06-10 09:53
After this problem, I commented out a couple of lines as below and tried again. The build completed.
<img width="334" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/90482370/3fa90b4d-ed2f-4596-94f2-18fc8a5f18c9">

**Comment by tobitege** [comment] 2024-06-10 09:54
You should put that in your first post, vital information. 😀

**Comment by SmartManoj** [comment] 2024-06-10 10:09
Duplicate of https://github.com/OpenDevin/OpenDevin/issues/2330

**Comment by tobitege** [comment] 2024-06-10 10:13
oh, great catch @SmartManoj, as always!

@edwardbrazier it might just have overlapped time-wise, but try again with a current main branch.

**Closed** 2024-06-10 10:28 UTC
Labels: bug
