### ISSUE TITLE
Gemini is not in the list of models

### ISSUE THREAD

**Issue by YasarAbi** [OpenDevin/OpenDevin#591] opened 2024-04-02 16:32 UTC
![image](https://github.com/OpenDevin/OpenDevin/assets/73652808/5dfb8ea5-640f-4bb7-a2be-f5821353bfe9)

**Comment by timucindusunur** [comment] 2024-04-02 16:43
OpenDevin Çalışma Alanı Dizini
./work

Modeli
gpt-4

Ajan
PlannerAgent

**Comment by timucindusunur** [comment] 2024-04-02 16:50
config.toml

LLM_API_KEY="..."
LLM_MODEL="gemini/gemini-pro"
WORKSPACE_DIR="./work"

**Comment by timucindusunur** [comment] 2024-04-02 16:51
bende çalişti.

**Comment by rbren** [comment] 2024-04-02 21:16
Confirmed this is a problem. Shouldn't be the case: https://docs.litellm.ai/docs/providers/gemini

Looks like we're not getting the right list of providers from LiteLLM

**Comment by foragerr** [comment] 2024-04-02 21:53
I'll take a shot at this.

**Comment by YasarAbi** [comment] 2024-04-02 22:16
> Confirmed this is a problem. Shouldn't be the case: https://docs.litellm.ai/docs/providers/gemini
> 
> Looks like we're not getting the right list of providers from LiteLLM

Ask OpenDevin. It should fix it :)

**Comment by maestrocoder** [comment] 2024-04-02 23:47
let me know @foragerr if you get a branch up on this, i'm interested for this purpose - got gemini pro 1.5 api working with the 1M tokens, excited to light up open-devin and add custom whisper speech to text feature so we are just talk to my agents

**Comment by foragerr** [comment] 2024-04-03 00:12
Seems to be an issue with litellm. 
Raised a PR in their repo. https://github.com/BerriAI/litellm/issues/2803

**Comment by azmodeuz** [comment] 2024-04-03 09:35
any updates on this? i would also like to try gemini

**Comment by timucindusunur** [comment] 2024-04-03 12:55
The new update broke it its not working. Gemini Pro!
Also, there are 1500 options, but no Gemini, which is interesting.

**Comment by foragerr** [comment] 2024-04-03 13:19
Upstream PR is now merged.
If you use `litellm==v1.34.22`, you will see gemini in the drop down box.

https://github.com/BerriAI/litellm/releases/tag/v1.34.22

**Comment by xcodebuild** [comment] 2024-04-03 13:46
The latest code can already see gemini, https://github.com/OpenDevin/OpenDevin/pull/641 accidentally fixed the problem LOL.

<img width="498" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/5436704/895c7415-4add-41d3-8fe7-27d10d3ca51a">

**Comment by foragerr** [comment] 2024-04-03 14:37
> https://github.com/OpenDevin/OpenDevin/pull/641 accidentally fixed the problem LOL.

No it didn't. This did: https://github.com/BerriAI/litellm/pull/2806

**Closed** 2024-04-04 03:02 UTC
Labels: good first issue, backend
