### ISSUE TITLE
Invalid `config.toml` configuration when using local model.

### ISSUE THREAD

**Issue by zhonggegege** [OpenDevin/OpenDevin#843] opened 2024-04-07 04:38 UTC
When using local models, the config.toml configuration must be configured according to the models listed on the front end (including the full model path), otherwise the front-end model list will be set to ·null· by default, which will result in failure to run. If config is configured according to the front-end model list. Does toml have a reference standard? Because the model name path here cannot be modified. For example: Even if the model name in the front-end model list exists in local servers such as "LM Studio" and "ollama", after being configured with multiple LLM_MODEL="" methods, "null" will still be displayed on the front-end, unless it is completely consistent with the front-end model list. The method "LLM_MODEL="ollama/llama2:13b-chat-q4_K_M/"" is the only one because their model name paths are consistent.
![image](https://github.com/OpenDevin/OpenDevin/assets/152971528/fcd674b9-f13c-43c8-b59b-6ddd809896c1)

config.toml------------------------------
LLM_MODEL="TheBloke/deepseek-coder-33B-instruct-GGUF"
LLM_API_KEY="lm-studio"
LLM_EMBEDDING_MODEL=""
LLM_BASE_URL="http://192.168.0.93:1234/v1"
WORKSPACE_DIR="./workspace"

logs----------------------------------
raise litellm.exceptions.BadRequestError(  # type: ignore
litellm.exceptions.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=null
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers

**Comment by flavioTocca** [comment] 2024-04-07 08:06
try to modify the llm.py file located in opendevin/opendevin/llm, as per the screen we give priority to the config file, even if I currently can't get the answers back from lm studio

![llmModify](https://github.com/OpenDevin/OpenDevin/assets/64084046/0c1f43f7-8a3a-41d7-8234-14c44df6c483)

**Comment by risingsunomi** [comment] 2024-04-07 08:34
I am getting the same type of issue but running on purely Windows with the powershell install

Currently my toml file is 

```
LLM_MODEL = "qwen"
LLM_EMBEDDING_MODEL = "llama2"
LLM_BASE_URL = "http://127.0.0.1:11434"
WORKSPACE_DIR = "E:\\Projects\\PowerShell\\OpenDevinPowerShell\\opendevin_env\\OpenDevin\\workspace"
```

Without an LLM_API_KEY defined as I am trying to get it to run locally with ollama.

In OpenDevin/opendevin/server/agent/manager.py in function create_controller, defaults should be loaded from the config but LLM_MODEL is replaced with the default in the script, "gpt-3.5-turbo-1106". This might be an issue with OpenDevin/opendevin/config.py and get_or_default where that function is returning values, if in, the toml or using the default static config in config.py. This is causing LLM_MODEL and LLM_EMBEDDING_MODEL to be ignored.

From this log you see the embedding model ignored along with the LLM_MODEL

```
embedding_strategy: "llama2"

--- opendevin ignoring embedding model and using huggingface
INFO:sentence_transformers.SentenceTransformer:Load pretrained SentenceTransformer: BAAI/bge-small-en-v1.5
04:12:06 - sentence_transformers.SentenceTransformer:INFO: SentenceTransformer.py:107 - Load pretrained SentenceTransformer: BAAI/bge-small-en-v1.5
INFO:sentence_transformers.SentenceTransformer:2 prompts are loaded, with the keys: ['query', 'text']
04:12:08 - sentence_transformers.SentenceTransformer:INFO: SentenceTransformer.py:224 - 2 prompts are loaded, with the keys: ['query', 'text']
---

DEFAULT_API_KEY None
DEFAULT_BASE_URL http://127.0.0.1:11434
LLM_MODEL "qwen"
DEFAULT_WORKSPACE_DIR "E:\Projects\PowerShell\OpenDevinPowerShell\opendevin_env\OpenDevin\workspace"
CONTAINER_IMAGE ghcr.io/opendevin/sandbox

--- OpenDevin ignoring above toml config and defaulting to gpt-3.5-turbo
Adding Router
{'model_name': 'gpt-3.5-turbo-1106', 'litellm_params': {'model': 'gpt-3.5-turbo-1106', 'api_key': None, 'api_base': 'http://127.0.0.1:11434'}}
---
```

Import config.py interactively you can see it treats the quoted "qwen" as a whole string with double quotes

```python
>>> from opendevin import config
>>> config.get_or_default("LLM_MODEL", "gpt-3.5-turbo-1106")
'"qwen"'
```

**Comment by flavioTocca** [comment] 2024-04-07 08:42
@risingsunomi if you change the if else in the file as I wrote above it gives the priority locally, however I have another problem where lm studio does not return the response to devin

**Comment by risingsunomi** [comment] 2024-04-07 08:45
> @risingsunomi if you change the if else in the file as I wrote above it gives the priority locally, however I have another problem where lm studio does not return the response to devin

Thank you, will try. I just wonder if the call before llm.py by the server manager or the main is overwritting it as I am seeing it correctly passed when llm.py is loaded but when the llm class is called in main.py or the settings changed via manager.py it drops what the toml was. 

Will try this change and hopefully we can make a PR to fix all these toml issues.

**Comment by flavioTocca** [comment] 2024-04-07 08:54
the project is very large, I haven't understood the whole thing yet, I tried and there was the only point I found that gave priority to the toml. I hope you find some solutions, I've been stuck with lm studio for 3 days with this issue #812

**Comment by zhonggegege** [comment] 2024-04-07 08:55
> @risingsunomi if you change the if else in the file as I wrote above it gives the priority locally, however I have another problem where lm studio does not return the response to devin

If so, what's the point of modifying it?

**Comment by flavioTocca** [comment] 2024-04-07 09:00
@zhonggegege you can try and see if it works maybe you don't have my problem, because you have some different settings there is this possibility, or don't use lm studio because from what I see a real solution hasn't been found yet

**Comment by zhonggegege** [comment] 2024-04-07 09:38
> @zhonggegege you can try and see if it works maybe you don't have my problem, because you have some different settings there is this possibility, or don't use lm studio because from what I see a real solution hasn't been found yet

thank you for your reply.

**Comment by risingsunomi** [comment] 2024-04-07 10:35
Ok I think I found the solution and got it working with ollama/qwen. It was because in the front end there was the default openai model being sent in the initialization message to the backend over websockets.

![image](https://github.com/OpenDevin/OpenDevin/assets/1927935/52636e00-b2e2-402a-9455-1dbde3935053)

I have updated **OpenDevin/opendevin/server/agent/manager.py** to kinda do what @flavioTocca llm.py update did where just making sure the environment variables are focused on first. 

![image](https://github.com/OpenDevin/OpenDevin/assets/1927935/418db2f0-3451-498a-97d7-bb8e726ad300)

Going to make a PR with this update and hope you can get it working.

**Comment by risingsunomi** [comment] 2024-04-07 11:14
I updated the code in the screenshot as that wouldn't let the frontend update the backend settings. Made a PR and have the newest code there

**Comment by flavioTocca** [comment] 2024-04-07 11:35
@risingsunomi iI tried the code you ran, removing my part doesn't seem to work
![Uploading modelnull.png…]()

**Comment by risingsunomi** [comment] 2024-04-07 11:38
> @risingsunomi i try the code you ran, removing my part doesn't seem to work
> 
> ![modelnull](https://github.com/OpenDevin/OpenDevin/assets/64084046/61363db7-3086-4956-897e-dcb766c2a95d)
> 
> 
> 
> 

I got that error when I didn't type in the model that litellm wants it in. Might have to look at their page for your model and see if you have it in the format they need. 

For example, I was using quen and not ollama/quen

**Comment by flavioTocca** [comment] 2024-04-07 11:47
and why does editing llm.py see it instead? however this is not my issue it was just to give a hint for those who want to start it locally by forcing it, I return to my problem which was closed

**Comment by 2868151647** [comment] 2024-04-07 12:54
@risingsunomi i have a question, i got 'ollama/llama2' from '/api/default-model', i think it should be lcoalStorage.setItem('model'), but i dont see it in my browser. in websocket model set with 'gpt-3.5-turbo-1106'. sorry im not familiar with react i tried, maybe some bugs there.

**Comment by lowlyocean** [comment] 2024-04-07 14:32
@iFurySt can you check if the PR above #858 is compatible with the one you proposed #863 ?

**Comment by iFurySt** [comment] 2024-04-07 14:47
> @iFurySt can you check if the PR above #858 is compatible with the one you proposed #863 ?

i think #858 doesn't need to be merged~ cuz my changes will overwrite it. 😅

**Comment by lowlyocean** [comment] 2024-04-07 15:52
@risingsunomi I just checked @iFurySt 's PR and it seems to work for me. Can you confirm your PR #858 is no longer needed and can be closed?

**Comment by risingsunomi** [comment] 2024-04-07 18:17
> @risingsunomi I just checked @iFurySt 's PR and it seems to work for me. Can you confirm your PR #858 is no longer needed and can be closed?

Confirmed and closed my PR. @iFurySt appreciate the hard work on this, thank you.

**Comment by rbren** [comment] 2024-04-07 20:27
Sounds like this is fixed now that @iFurySt's PR is in. LMK if not!

**Closed by rbren** 2024-04-07 20:27 UTC
Labels: bug
