### ISSUE TITLE
config.toml conflicts with front-end settings

### ISSUE THREAD

**Issue by zhonggegege** [OpenDevin/OpenDevin#814] opened 2024-04-06 09:10 UTC
config.toml seems to conflict with the front-end settings, after starting the front-end with the parameters set in config.toml, the error log is always related to the settings in the front-end, and if you select a model in the settings, it cannot be modified, and there is no such thing in ollama Model downloads with relevant names. For example, if a model is set in config.toml and the model is not specified in the front-end settings, the front-end log will always prompt: "LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=null
  Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers”
A model is selected in the front-end settings, but there is no model with the corresponding name in ollama to download.
![image](https://github.com/OpenDevin/OpenDevin/assets/152971528/7a5adc6f-7088-4b2c-a2f5-b9826f52493c)

**Comment by lowlyocean** [comment] 2024-04-06 10:53
Looks like a duplicate of (or at least related to)
https://github.com/OpenDevin/OpenDevin/issues/793

**Comment by enyst** [comment] 2024-04-06 17:36
A fix to mitigate the issue has been merged. Please try to pull again and ```make build```.

I'll close this one because it is a duplicate, but the issue is tracked here https://github.com/OpenDevin/OpenDevin/issues/793

**Closed** 2024-04-06 17:37 UTC
Labels: bug
