### ISSUE TITLE
[Bug]: Issue with workspace display

### ISSUE THREAD

**Issue by CmetankaJDD** [OpenDevin/OpenDevin#2000] opened 2024-05-23 13:34 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

The issue is that the workspace is not displaying.

### Current Version

```bash
I am using the latest version from GitHub
```

### Installation and Configuration

```bash
I performed the installation using the following commands:
git clone https://github.com/OpenDevin/OpenDevin.git
make build
make run
```

### Model and Agent

Model: groq/llama3-8b-8192
Agent: CodeActAgent

### Reproduction Steps

Start the Docker containers.
Open the user interface.
Navigate to the workspace section.

### Logs, Errors, Screenshots, and Additional Context

The problem is that the workspace interface is not displaying, although all installation steps were followed correctly.
![2024-05-23_14 10 12](https://github.com/OpenDevin/OpenDevin/assets/124920865/c549b746-9b51-46ce-87a1-f83b69f2550a)

**Comment by SmartManoj** [comment] 2024-05-23 13:40
any error in logs?

**Comment by CmetankaJDD** [comment] 2024-05-23 13:42
Running the app...
Starting backend server...
Waiting for the backend to start...
INFO:     Started server process [10363]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
Connection to localhost port 3000 [tcp/hbci] succeeded!
Backend started successfully.
Starting frontend with npm...

> opendevin-frontend@0.1.0 start
> npm run make-i18n && vite --port 3001


> opendevin-frontend@0.1.0 make-i18n
> node scripts/make-i18n-translations.cjs


  VITE v5.2.11  ready in 576 ms

  ➜  Local:   http://localhost:3001/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
INFO:     127.0.0.1:54717 - "GET /api/options/models HTTP/1.1" 200 OK
INFO:     127.0.0.1:54718 - "GET /api/options/models HTTP/1.1" 200 OK
INFO:     127.0.0.1:54719 - "GET /api/options/agents HTTP/1.1" 200 OK
INFO:     127.0.0.1:54720 - "GET /api/options/agents HTTP/1.1" 200 OK
INFO:     ('127.0.0.1', 54722) - "WebSocket /ws?token=" [accepted]
INFO:     connection open
14:04:58 - opendevin:INFO: agent.py:64 - Using server runtime
14:04:58 - opendevin:INFO: ssh_box.py:208 - SSHBox is running as opendevin user with USER_ID=501 in the sandbox
14:04:58 - opendevin:INFO: ssh_box.py:642 - Container stopped
14:04:58 - opendevin:WARNING: ssh_box.py:654 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information.
14:04:58 - opendevin:INFO: ssh_box.py:627 - Mounting workspace directory: /Users/a1234/Desktop/OpenDevin/workspace
14:04:58 - opendevin:INFO: ssh_box.py:663 - Mounting volumes: {'/Users/a1234/Desktop/OpenDevin/workspace': {'bind': '/workspace', 'mode': 'rw'}, '/tmp/cache': {'bind': '/home/opendevin/.cache', 'mode': 'rw'}}
14:04:58 - opendevin:INFO: ssh_box.py:627 - Mounting workspace directory: /Users/a1234/Desktop/OpenDevin/workspace
14:04:59 - opendevin:INFO: ssh_box.py:674 - Container started
14:05:00 - opendevin:INFO: ssh_box.py:690 - waiting for container to start: 1, container status: running
14:05:00 - opendevin:INFO: ssh_box.py:377 - Connecting to opendevin@localhost via ssh. If you encounter any issues, you can try `ssh -v -p 54723 opendevin@localhost` with the password '561476f0-8d85-44c4-9a69-03377f273bb2' and report the issue on GitHub. If you started OpenDevin with `docker run`, you should try `ssh -v -p 54723 opendevin@localhost` with the password '561476f0-8d85-44c4-9a69-03377f273bb2 on the host machine (where you started the container).
14:05:02 - opendevin:INFO: browser_env.py:38 - Starting browser env...
14:05:06 - opendevin:INFO: browser_env.py:53 - Browser env started.
14:05:06 - opendevin:INFO: agent.py:96 - Creating agent CodeActAgent using LLM groq/llama3-8b-8192
14:05:06 - opendevin:INFO: llm.py:119 - Initializing LLM with model: groq/llama3-8b-8192
14:05:06 - opendevin:INFO: mixin.py:31 - Copied files from [/Users/a1234/Desktop/OpenDevin/opendevin/runtime/plugins/jupyter] to [/opendevin/plugins/jupyter] inside sandbox.
14:05:06 - opendevin:INFO: mixin.py:39 - Initializing plugin [jupyter] by executing [/opendevin/plugins/jupyter/setup.sh] in the sandbox.
14:05:10 - opendevin:INFO: mixin.py:53 - Plugin jupyter initialized successfully
14:05:10 - opendevin:INFO: mixin.py:31 - Copied files from [/Users/a1234/Desktop/OpenDevin/opendevin/runtime/plugins/swe_agent_commands] to [/opendevin/plugins/swe_agent_commands] inside sandbox.
14:05:10 - opendevin:INFO: mixin.py:39 - Initializing plugin [swe_agent_commands] by executing [/opendevin/plugins/swe_agent_commands/setup_default.sh] in the sandbox.
14:05:11 - opendevin:INFO: mixin.py:53 - Plugin swe_agent_commands initialized successfully
14:05:11 - opendevin:INFO: mixin.py:67 - Sourced ~/.bashrc successfully
14:05:11 - opendevin:ERROR: state.py:54 - Failed to restore state from session: sessions/1c361b3f-d64d-4e78-8b18-d115b2f85ce6/agent_state.pkl
Error restoring state sessions/1c361b3f-d64d-4e78-8b18-d115b2f85ce6/agent_state.pkl
14:05:11 - opendevin:INFO: agent_controller.py:158 - Setting agent(CodeActAgent) state from AgentState.LOADING to AgentState.INIT
INFO:     127.0.0.1:54727 - "GET /api/list-files?path=/ HTTP/1.1" 200 OK

**Comment by SmartManoj** [comment] 2024-05-23 14:35
> 14:05:11 - opendevin:ERROR: state.py:54 - Failed to restore state from session: sessions/1c361b3f-d64d-4e78-8b18-d115b2f85ce6/agent_state.pkl
> Error restoring state sessions/1c361b3f-d64d-4e78-8b18-d115b2f85ce6/agent_state.pkl

**Comment by SmartManoj** [comment] 2024-05-23 14:46
Refresh the page as /index.html is already loaded. Any errors in the console?

**Comment by CmetankaJDD** [comment] 2024-05-23 15:09
<details> <summary>In the user's error at the link https://github.com/OpenDevin/OpenDevin/issues/1988, the workspace is also missing</summary> This can also be seen in their screenshot. </details>

**Comment by SmartManoj** [comment] 2024-05-23 15:10
He clicked the browser tab.

**Comment by CmetankaJDD** [comment] 2024-05-23 15:20
In the workspace folder, it is also empty if you ask OpenDevIn to write any code.

**Comment by SmartManoj** [comment] 2024-05-23 15:31
After refreshing the page, any new error in the log?

**Comment by CmetankaJDD** [comment] 2024-05-23 15:35
browser console or the VSCode logs?

**Comment by SmartManoj** [comment] 2024-05-23 15:35
VSCode logs?

**Comment by CmetankaJDD** [comment] 2024-05-23 15:37
There are no errors in the logs.

**Comment by CmetankaJDD** [comment] 2024-05-23 15:38
```
State.INIT to AgentState.STOPPED
6:36:09 PM [vite] ws proxy socket error:
Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:952:11)
    at Socket._write (node:net:964:8)
    at writeOrBuffer (node:internal/streams/writable:564:12)
    at _write (node:internal/streams/writable:493:10)
    at Writable.write (node:internal/streams/writable:502:10)
    at Socket.ondata (node:internal/streams/readable:1007:22)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
18:36:09 - opendevin:INFO: browser_env.py:60 - SHUTDOWN recv, shutting down browser env...

**Comment by CmetankaJDD** [comment] 2024-05-23 15:46
[opendevin_2024-05-23.log](https://github.com/OpenDevin/OpenDevin/files/15419259/opendevin_2024-05-23.log)

**Comment by SmartManoj** [comment] 2024-05-23 15:50
Could you open in incognito window?

**Comment by CmetankaJDD** [comment] 2024-05-23 15:55
<img width="886" alt="Снимок экрана 2024-05-23 в 18 55 15" src="https://github.com/OpenDevin/OpenDevin/assets/124920865/f65753ca-be5b-41ab-a731-43f897285fef">

**Comment by amanape** [comment] 2024-05-23 20:23
It seems this is a duplicate of #1997

**Closed by amanape** 2024-05-23 20:23 UTC
Labels: bug, frontend, severity:critical

**Comment by SmartManoj** [comment] 2024-05-24 01:51
But the OP of #1997 started the server with 8 workers.

**Comment by amanape** [comment] 2024-05-24 06:00
@SmartManoj But it seems that the underlying issue with the file reader is the same. So they would both be resolved with the same fix, don't you think? If not, feel free to reopen it 😅
