### ISSUE TITLE
Annoying bug... Oops. Something went wrong. Wiping my credits

### ISSUE THREAD

**Issue by thelege2nd** [OpenDevin/OpenDevin#487] opened 2024-04-01 07:13 UTC
im getting the message below in the first 20 seconds of starting a task. Happens with all models.

Oops. Something went wrong: Error condensing thoughts: Expecting value: line 1 column 1 (char 0)

it also is sending tokens and wiping out my credits although no messages or errors are showing other than the one above and chatting with Devin does not do anything and i have to refresh to start over. I suspect it happens with Devin browse the internet.

![image](https://github.com/OpenDevin/OpenDevin/assets/12984941/dd308659-ad0f-4613-a818-e52e8cc1b7c8)

**Comment by enyst** [comment] 2024-04-01 08:00
Do you have the latest version? Please make sure you pull it again.

**Comment by tsbertalan** [comment] 2024-04-01 19:24
This is #444 and #465 , I think.

**Comment by rbren** [comment] 2024-04-02 11:20
This looks like a dupe of https://github.com/OpenDevin/OpenDevin/issues/495

I also see the `unexpected keyword file` issue, which should be fixed in main

**Closed by rbren** 2024-04-02 11:20 UTC
Labels: bug
