### ISSUE TITLE
interactive terminal?

### ISSUE THREAD

**Issue by charliez0** [OpenDevin/OpenDevin#3008] opened 2024-07-19 03:34 UTC
**What problem or use case are you trying to solve?**
running some commands requiring interactive stuck and cannot exit
**Describe the UX of the solution you'd like**

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by SmartManoj** [comment] 2024-07-19 03:49
Could you please mention the command to check for alternatives?

**Comment by charliez0** [comment] 2024-07-19 04:28
easy, eg: bash python3 and so on

**Comment by SmartManoj** [comment] 2024-07-19 04:30
workaround: you can run using `python3 -c 'commands'`

> cannot exit

It will exit after the timeout occurs (2 mins)

**Comment by charliez0** [comment] 2024-07-19 06:31
> workaround: you can run using `python3 -c "commands"`
> 
> > cannot exit
> 
> It will exit after the timeout occurs (2 mins)

I know that, but it's not the final solution though

**Comment by tobitege** [comment] 2024-07-19 07:38
This is basically a duplicate of #2754
 
@charliez0 we are aware of the issue but there's no elegant solution to this right now.

**Comment by xingyaoww** [comment] 2024-07-19 16:00
I just created a mega-issue to track similar issues caused by the same problem: https://github.com/OpenDevin/OpenDevin/issues/3031

Hopefully, we can fix this soon! Contributions to this problem are welcomed, too! I feel this is a bit hard to resolve in a general manner :(

**Comment by tobitege** [comment] 2024-07-20 13:53
Since we have above tracker issue, closing this one

**Closed by tobitege** 2024-07-20 13:53 UTC
Labels: enhancement
