### ISSUE TITLE
Directory not found on Windows

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#301] opened 2024-03-28 13:35 UTC
Task exception was never retrieved
future: <Task finished name='create controller' coro=<Session.create_controller() done, defined at C:\Users\pierr\OpenDevin\opendevin\server\session.py:76> exception=AssertionError('Directory "C:/Users/pierr/OpenDevinProjects" does not exist.')>
Traceback (most recent call last):
  File "C:\Users\pierr\OpenDevin\opendevin\server\session.py", line 92, in create_controller
    self.controller = AgentController(self.agent, directory, callbacks=[self.on_agent_event])
  File "C:\Users\pierr\OpenDevin\opendevin\controller.py", line 14, in __init__
    self.command_manager = CommandManager(workdir)
  File "C:\Users\pierr\OpenDevin\opendevin\lib\command_manager.py", line 22, in __init__
    self.shell = DockerInteractive(id="default", workspace_dir=dir)
  File "C:\Users\pierr\OpenDevin\opendevin\sandbox\sandbox.py", line 30, in __init__
    assert os.path.exists(workspace_dir), f"Directory {workspace_dir} does not exist."
AssertionError: Directory "C:/Users/pierr/OpenDevinProjects" does not exist.

**Comment by iFurySt** [comment] 2024-03-28 14:06
you need to provide more information before we can help you. please use the issue template :)

**Comment by PierrunoYT** [comment] 2024-03-28 14:13
I set everything up on windows with set instead of export and added the path to the project folder but soon as I start front and backend its broken and it throws me this error.

**Comment by RohitX0X** [comment] 2024-03-28 14:43
Just an intuitive guess , 
Your Directory has '/' instead of '\'

**Comment by PierrunoYT** [comment] 2024-03-28 14:54
> Just an intuitive guess , Your Directory has '/' instead of '\'

I tried bot but did not worked

**Comment by PierrunoYT** [comment] 2024-03-28 17:01
https://github.com/OpenDevin/OpenDevin/issues/301

**Comment by PierrunoYT** [comment] 2024-03-28 17:02
![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/2d632862-eaca-4e6a-b9e5-8cc4a62e6678)

**Comment by rbren** [comment] 2024-03-28 17:04
> Just an intuitive guess ,
> Your Directory has '/' instead of '\'

This does seem suspect! 

What does this show:
```
python opendevin/main.py -d "C:\Users\pierr\OpenDevinProjects" -t "create a TODO list web app"
```

**Comment by PierrunoYT** [comment] 2024-03-28 17:05
> > Just an intuitive guess ,
> > Your Directory has '/' instead of ''
> 
> This does seem suspect!
> 
> What does this show:
> 
> ```
> python opendevin/main.py -d "C:\Users\pierr\OpenDevinProjects" -t "create a TODO list web app"
> ```

![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/a5ebd1cd-c366-4ac9-b43d-2dd677df7342)

**Comment by rbren** [comment] 2024-03-28 17:19
ah try
```
PYTHONPATH=`pwd` python opendevin/main.py -d "C:\Users\pierr\OpenDevinProjects" -t "create a TODO list web app"
```

**Comment by PierrunoYT** [comment] 2024-03-28 17:23
> ah try
> 
> ```
> PYTHONPATH=`pwd` python opendevin/main.py -d "C:\Users\pierr\OpenDevinProjects" -t "create a TODO list web app"
> ```

C:\Users\pierr\OpenDevin>set PYTHONPATH=%cd% && python opendevin/main.py -d "C:\Users\pierr\OpenDevinProjects" -t "create a TODO list web app"
C:\Users\pierr\AppData\Local\Programs\Python\Python312\Lib\site-packages\onnxruntime\capi\onnxruntime_validation.py:26: UserWarning: Unsupported Windows version (11). ONNX Runtime supports Windows 10 and above, only.
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\pierr\OpenDevin\opendevin\main.py", line 5, in <module>
    import agenthub # noqa F401 (we import this to get the agents registered)
    ^^^^^^^^^^^^^^^
  File "C:\Users\pierr\OpenDevin\agenthub\__init__.py", line 2, in <module>
    from . import codeact_agent
  File "C:\Users\pierr\OpenDevin\agenthub\codeact_agent\__init__.py", line 12, in <module>
    assert (
AssertionError: Please set the OPENAI_API_KEY environment variable.

**Comment by PierrunoYT** [comment] 2024-03-28 17:23
I wantt to set it permanently. Right now I need to add this everytime I start it.

**Comment by rbren** [comment] 2024-03-28 19:27
Yes, you'll need a solution like `direnv` to manage your environment variables. We might be able to support a config file at some point

**Comment by Zoyashah01** [comment] 2024-03-28 20:05
Encounter "Directory not found on Windows" exclusively at Restaurants in Dubai Mall. Troubleshoot and resolve this issue related to missing directories, ensuring seamless operation of your Windows environment. Just as Restaurants in Dubai Mall offers a diverse array of dining options, this opportunity provides essential guidance for resolving directory-related errors effectively. Address the issue promptly to maintain the integrity and functionality of your system. Access exclusive content now at [Restaurants in Dubai Mall!](https://wowdeals360.com/blog/all-you-need-to-know-about-dubai-mall/)

**Comment by rbren** [comment] 2024-03-29 13:23
You've still got `/` instead of `\`

**Comment by PierrunoYT** [comment] 2024-03-29 13:26
So the readme is wrong then it's using /

**Comment by rbren** [comment] 2024-03-29 13:33
You're on Windows. Everything is different on Windows. Blame microsoft 😛  I hear they're making it better though...

You might want to try WSL https://learn.microsoft.com/en-us/windows/wsl/install

**Comment by AbdelrahmanHassan111** [comment] 2024-03-29 14:53
you can enable WSL by running the following command `dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart `
make sure you running it **as administrator**

then choose a Linux distribution and install it 

then update and install the packages by running the following command `sudo apt update`

at the end you can access for your WSL by running in the terminal `wsl`

and you can access on our windows files by using `/mnt / YOUR PATH`

**Comment by rbren** [comment] 2024-03-29 15:59
Setting up WSL is definitely outside the scope of this project 😄 

You'll need to work a bit on getting your workstation to a point where you can run python programs from GitHub.

Eventually, maybe we'll manage to package OpenDevin up with installers for OS X, Windows, and Linux. But we're _really_ far from being able to offer first-class support for different operating systems.

**Closed by rbren** 2024-03-29 15:59 UTC

**Comment by AbdelrahmanHassan111** [comment] 2024-03-29 16:07
@PierrunoYT at the beginning the problem is : you did not set the **OPENAI API Key** so check this again and it will works
