### ISSUE TITLE
Error creating controller: Could not establish connection to host

### ISSUE THREAD

**Issue by jamincollins** [OpenDevin/OpenDevin#1068] opened 2024-04-13 02:55 UTC
#### Describe the bug

20:49:36 - opendevin:ERROR: agent.py:136 - Error creating controller: Could not establish connection to host

#### Setup and configuration
**Current version**:

```bash
commit 2326312d3a297a5027b83018c0a5e0421ff74285 (HEAD -> main, origin/main, origin/HEAD)
Author: Leo <ifuryst@gmail.com>
Date:   Sat Apr 13 10:18:34 2024 +0800

    fix: print the wrong ssh port number (#1054)
```

Arch Linux

**My config.toml and environment vars** (be sure to redact API keys):
```toml
$ cat config.toml
LLM_MODEL="ollama/codellama"
LLM_API_KEY="ollama"
LLM_EMBEDDING_MODEL="local"
LLM_BASE_URL="http://localhost:11434"
WORKSPACE_DIR="./workspace"
```

**My model and agent** (you can see these settings in the UI):
* Model: ollama/codellama
* Agent:

**Commands I ran to install and run OpenDevin**:
```
ollama pull codellama

make build
make run
```

**Steps to Reproduce**:
1. fetch codellama for ollama
2. start ollama with the codellama model
3. configure OpenDevin (see above)
4. build OpenDevin
5. run OpenDevin

**Logs, error messages, and screenshots**:
```
INFO:     Started server process [1943339]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
INFO:     ('127.0.0.1', 52362) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiIwYzMxOTkyMS1hOTI1LTQ2ZDAtYjdlMS03MzcxNGY1YWQzNTgifQ.G8gIdPz9tgqpV1wAPpQMH042ZhZX9kyjadrtvTupNGg" [accepted]
Starting loop_recv for sid: 0c319921-a925-46d0-b7e1-73714f5ad358
INFO:     connection open
INFO:     127.0.0.1:52366 - "GET /refresh-files HTTP/1.1" 200 OK
INFO:     127.0.0.1:52382 - "GET /messages/total HTTP/1.1" 200 OK
INFO:     127.0.0.1:52380 - "GET /configurations HTTP/1.1" 200 OK
INFO:     127.0.0.1:52390 - "GET /refresh-files HTTP/1.1" 200 OK
20:49:33 - opendevin:INFO: ssh_box.py:80 - Using workspace directory: /home/jamin/proj/OpenDevin/workspace
20:49:34 - opendevin:INFO: ssh_box.py:280 - Container stopped
20:49:35 - opendevin:INFO: ssh_box.py:312 - Container started
20:49:36 - opendevin:INFO: ssh_box.py:329 - waiting for container to start: 1, container status: running
20:49:36 - opendevin:INFO: ssh_box.py:169 - Connecting to opendevin@localhost via ssh. If you encounter any issues, you can try `ssh -v -p 45241 opendevin@localhost` with the password '29e14b7c-6b0f-4567-b697-4371575d4e72' and report the issue on GitHub.
20:49:36 - opendevin:ERROR: agent.py:136 - Error creating controller: Could not establish connection to host
Traceback (most recent call last):
  File "/home/jamin/proj/OpenDevin/opendevin/server/agent/agent.py", line 126, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/home/jamin/proj/OpenDevin/opendevin/controller/agent_controller.py", line 92, in __init__
    self.command_manager = CommandManager(
                           ^^^^^^^^^^^^^^^
  File "/home/jamin/proj/OpenDevin/opendevin/controller/command_manager.py", line 26, in __init__
    self.shell = DockerSSHBox(
                 ^^^^^^^^^^^^^
  File "/home/jamin/proj/OpenDevin/opendevin/sandbox/ssh_box.py", line 98, in __init__
    self.start_ssh_session()
  File "/home/jamin/proj/OpenDevin/opendevin/sandbox/ssh_box.py", line 174, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password, port=self._ssh_port)
  File "/home/jamin/.cache/pypoetry/virtualenvs/opendevin-KV-LMp1f-py3.11/lib/python3.11/site-packages/pexpect/pxssh.py", line 424, in login
    raise ExceptionPxssh('Could not establish connection to host')
pexpect.pxssh.ExceptionPxssh: Could not establish connection to host
```

**Comment by jamincollins** [comment] 2024-04-13 03:19
near as I can tell, the referenced SSH server is not running

**Comment by souravzzz** [comment] 2024-04-13 03:19
Seems to be a OS X specific issue. Workaround: 

```diff
diff --git a/opendevin/sandbox/ssh_box.py b/opendevin/sandbox/ssh_box.py
index b053034..fcd8bed 100644
--- a/opendevin/sandbox/ssh_box.py
+++ b/opendevin/sandbox/ssh_box.py
@@ -89,7 +89,7 @@ class DockerSSHBox(Sandbox):

         # set up random user password
         self._ssh_password = str(uuid.uuid4())
-        self._ssh_port = find_available_tcp_port()
+        self._ssh_port = 2222 #find_available_tcp_port()

         # always restart the container, cuz the initial be regarded as a new session
         self.restart_docker_container()
```

**Comment by jamincollins** [comment] 2024-04-13 03:41
With that change, and shutting down the existing docker container, I was able to restart the build and run.  It now appears to be working, or at least accepting the task and consuming CPU cycles.  We'll see what it comes up with.

Thank you.

**Comment by souravzzz** [comment] 2024-04-13 05:33
@jamincollins Can you please reopen the ticket? My suggestion was a workaround. The bug should be fixed properly.

**Comment by nullnuller** [comment] 2024-04-13 11:29
I think the same issue exists in Ubuntu

**Comment by MEHColeman** [comment] 2024-04-13 15:31
I have this issue on Fedora when connecting to openai.
```
16:22:29 - opendevin:INFO: ssh_box.py:169 - Connecting to opendevin@localhost via ssh. If you encounter any issues, you can try `ssh -v -p 38517 opendevin@localhost` with the password '642615d6-6247-4e59-bc97-d3b394ee2331' and report the issue on GitHub.
16:22:29 - opendevin:ERROR: agent.py:136 - Error creating controller: Could not establish connection to host
Traceback (most recent call last):
  File "/home/mark/dev/personal/open_devin/opendevin/server/agent/agent.py", line 126, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/home/mark/dev/personal/open_devin/opendevin/controller/agent_controller.py", line 92, in __init__
    self.command_manager = CommandManager(
                           ^^^^^^^^^^^^^^^
  File "/home/mark/dev/personal/open_devin/opendevin/controller/command_manager.py", line 26, in __init__
    self.shell = DockerSSHBox(
                 ^^^^^^^^^^^^^
  File "/home/mark/dev/personal/open_devin/opendevin/sandbox/ssh_box.py", line 98, in __init__
    self.start_ssh_session()
  File "/home/mark/dev/personal/open_devin/opendevin/sandbox/ssh_box.py", line 174, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password, port=self._ssh_port)
  File "/home/mark/.cache/pypoetry/virtualenvs/opendevin-fny8eqy8-py3.12/lib/python3.12/site-packages/pexpect/pxssh.py", line 424, in login
    raise ExceptionPxssh('Could not establish connection to host')
pexpect.pxssh.ExceptionPxssh: Could not establish connection to host
```
The message suggests running an ssh command to debug:
```
 ssh -v -p 38517 opendevin@localhost
OpenSSH_9.3p1, OpenSSL 3.1.1 30 May 2023
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 20: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config.d/50-redhat.conf
debug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config
debug1: configuration requests final Match pass
debug1: re-parsing configuration
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 20: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config.d/50-redhat.conf
debug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config
debug1: Connecting to localhost [::1] port 38517.
debug1: connect to address ::1 port 38517: Connection refused
debug1: Connecting to localhost [127.0.0.1] port 38517.
debug1: connect to address 127.0.0.1 port 38517: Connection refused
ssh: connect to host localhost port 38517: Connection refused
```

The workaround about fixed it.

**Comment by souravzzz** [comment] 2024-04-13 19:20
I believe the issue is due to hardcoded 2222 port instead of ssh_port in https://github.com/OpenDevin/OpenDevin/blob/8b9f13b1ed4949bafc6dcfbe66d405ce5b4d7e3b/opendevin/sandbox/ssh_box.py#L303

**Comment by MrMoustache000** [comment] 2024-04-13 22:42
Same error over here. solved it adding SANDBOX_TYPE="exec" at end for config.toml

LLM_API_KEY="ollama"
LLM_MODEL="ollama/codellama:13b-python"
LLM_EMBEDDING_MODEL="ollama/nomic-embed-text"
LLM_BASE_URL="http://localhost:11434"
WORKSPACE_DIR="./workspace/snake_game"
SANDBOX_TYPE="exec"

**Comment by rbren** [comment] 2024-04-15 15:07
This should be fixed now that we're running in docker!

**Closed by rbren** 2024-04-15 15:07 UTC
Labels: bug

**Comment by jony-techexplorer** [comment] 2024-04-16 11:27
facing the same issue while running it through docker. OS : Zorin OS(Ubuntu)

**Comment by rbren** [comment] 2024-04-17 16:53
@jony-techexplorer can you open a new issue with the template filled out?
