### ISSUE TITLE
feature(frontend): Allow for resizing of chat interface and terminal panels

### ISSUE THREAD

**Issue by amanape** [OpenDevin/OpenDevin#3199] opened 2024-07-31 19:13 UTC
**What problem or use case are you trying to solve?**
Currently the panels have a minimum width/height and cannot resize below that minimum.

**Describe the UX of the solution you'd like**
Allow the user to resize freely until a certain point, one that is not too low (e.g., 0) or that breaks with the UI.
Alternatively, introduce toggles that can collapse the panels.

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**
These PRs attempted to address this issue but lacked certain things.
#3144 
#3125

**Comment by mamoodi** [comment] 2024-07-31 19:23
Duplicate of: https://github.com/OpenDevin/OpenDevin/issues/1745 ? Do you want to close that one and keep this one?

**Comment by amanape** [comment] 2024-07-31 19:30
@mamoodi I'm not sure to be honest. I would say this issue is a more specific version of #1745, but #1745 talks about a feature that is already implemented? I mean we could resize, just not less than a certain amount. It is not clear to me if #1745 addresses it in detail.

**Comment by mamoodi** [comment] 2024-07-31 19:36
The Terminal box and the box above it that contains Code Editor, Browser, Jupyter cannot be resized.
I see what you are saying, your specific use case is the minimum height.
Maybe if anyone takes it they can just take both :) 

* Allow resize of all windows + this issue

**Comment by amanape** [comment] 2024-08-12 20:18
@tobitege Do you find that #3330 resolved this issue? :smile:

**Comment by mamoodi** [comment] 2024-08-14 03:20
I can confirm that all the panels are resizable and we have toggles for collapse. Closing.

**Closed by mamoodi** 2024-08-14 03:20 UTC
Labels: enhancement, good first issue, frontend, severity:low, small effort
